# Generated by Django 6.0.6 on 2026-06-08 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('organizations', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(blank=True, help_text="Vide = workflow par défaut de l'entreprise.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='organizations.subsidiary', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'workflow de validation',
                'verbose_name_plural': 'workflows de validation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_date', models.DateField(db_index=True, verbose_name='date de la course')),
                ('departure_time', models.DateTimeField(verbose_name='heure de départ')),
                ('estimated_return', models.DateTimeField(verbose_name='heure estimée de retour')),
                ('origin', models.CharField(blank=True, max_length=255, verbose_name='point de départ')),
                ('destination', models.CharField(max_length=255, verbose_name='destination')),
                ('purpose', models.CharField(max_length=255, verbose_name='motif')),
                ('passengers', models.PositiveSmallIntegerField(default=1, verbose_name='nombre de passagers')),
                ('needs_driver', models.BooleanField(default=True, verbose_name="besoin d'un chauffeur")),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('normal', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='normal', max_length=12, verbose_name='priorité')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('pending_manager', 'En attente validation responsable'), ('pending_fleet', 'En attente validation flotte'), ('approved', 'Validée'), ('rejected', 'Refusée'), ('cancelled', 'Annulée'), ('vehicle_assigned', 'Véhicule affecté'), ('driver_assigned', 'Chauffeur affecté'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('closed', 'Clôturée')], db_index=True, default='draft', max_length=20, verbose_name='statut')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='drivers.driver', verbose_name='chauffeur affecté')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='demandeur')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.subsidiary', verbose_name='filiale')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='vehicles.vehicle', verbose_name='véhicule affecté')),
            ],
            options={
                'verbose_name': 'réservation',
                'verbose_name_plural': 'réservations',
                'ordering': ['-trip_date', '-departure_time'],
            },
        ),
        migrations.CreateModel(
            name='ReservationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='reservations/attachments/', verbose_name='fichier')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='libellé')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reservations.reservation', verbose_name='réservation')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
            },
        ),
        migrations.CreateModel(
            name='ReservationValidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('manager', 'Responsable hiérarchique'), ('fleet', 'Gestionnaire de flotte')], max_length=16, verbose_name='niveau')),
                ('decision', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='pending', max_length=12, verbose_name='décision')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='décidé le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='reservations.reservation', verbose_name='réservation')),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_validations', to=settings.AUTH_USER_MODEL, verbose_name='validateur')),
            ],
            options={
                'verbose_name': 'validation de réservation',
                'verbose_name_plural': 'validations de réservation',
                'ordering': ['reservation', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ordre')),
                ('level', models.CharField(choices=[('manager', 'Responsable hiérarchique'), ('fleet', 'Gestionnaire de flotte')], max_length=16, verbose_name='niveau')),
                ('is_required', models.BooleanField(default=True, verbose_name='obligatoire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='reservations.approvalworkflow', verbose_name='workflow')),
            ],
            options={
                'verbose_name': 'étape de validation',
                'verbose_name_plural': 'étapes de validation',
                'ordering': ['workflow', 'order'],
                'unique_together': {('workflow', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['subsidiary', 'status'], name='reservation_subsidi_8a49cc_idx'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['trip_date'], name='reservation_trip_da_a4b1e6_idx'),
        ),
    ]
