# Generated by Django 6.0.6 on 2026-06-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='heure de retour'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='trip_type',
            field=models.CharField(choices=[('one_way', 'Aller simple'), ('round_trip', 'Aller-retour')], default='one_way', max_length=12, verbose_name='type de trajet'),
        ),
    ]
