# Generated by Django 6.0.6 on 2026-07-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_return_time_reservation_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='flexibility_minutes',
            field=models.PositiveSmallIntegerField(default=0, help_text='Décalage acceptable du départ, pour permettre le partage de véhicule.', verbose_name='souplesse horaire (min)'),
        ),
    ]
