# Generated by Django 6.0.6 on 2026-06-08 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('organizations', '0001_initial'),
        ('reservations', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(max_length=255, verbose_name='destination')),
                ('status', models.CharField(choices=[('scheduled', 'Planifiée'), ('departed', 'Départ effectué'), ('in_progress', 'En cours'), ('returned', 'Retour effectué'), ('closed', 'Clôturée')], db_index=True, default='scheduled', max_length=16, verbose_name='statut')),
                ('actual_departure', models.DateTimeField(blank=True, null=True, verbose_name='départ réel')),
                ('actual_return', models.DateTimeField(blank=True, null=True, verbose_name='retour réel')),
                ('start_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='km au départ')),
                ('end_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='km au retour')),
                ('distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='distance parcourue (km)')),
                ('fuel_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='carburant consommé (L)')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='drivers.driver', verbose_name='chauffeur')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to=settings.AUTH_USER_MODEL, verbose_name='demandeur')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='reservations.reservation', verbose_name='réservation')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.subsidiary', verbose_name='filiale')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['-actual_departure', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('checkout', 'Remise (départ)'), ('checkin', 'Retour')], max_length=10, verbose_name='type')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='trips/signatures/', verbose_name='signature')),
                ('condition_notes', models.TextField(blank=True, verbose_name='état constaté')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='trips.trip', verbose_name='course')),
            ],
            options={
                'verbose_name': 'remise/retour',
                'verbose_name_plural': 'remises/retours',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField(verbose_name="date de l'incident")),
                ('severity', models.CharField(choices=[('minor', 'Mineur'), ('moderate', 'Modéré'), ('major', 'Majeur'), ('critical', 'Critique')], default='minor', max_length=12, verbose_name='gravité')),
                ('description', models.TextField(verbose_name='description')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='trips.trip', verbose_name='course')),
            ],
            options={
                'verbose_name': 'incident de course',
                'verbose_name_plural': 'incidents de course',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='TripPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='trips/photos/', verbose_name='photo')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='légende')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='trips.trip', verbose_name='course')),
            ],
            options={
                'verbose_name': 'photo de course',
                'verbose_name_plural': 'photos de course',
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['subsidiary', 'status'], name='trips_trip_subsidi_8ab119_idx'),
        ),
    ]
