# Generated by Django 6.0.6 on 2026-06-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_return_time_reservation_trip_type'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='leg',
            field=models.CharField(choices=[('outbound', 'Aller'), ('return', 'Retour')], db_index=True, default='outbound', max_length=10, verbose_name='segment'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='reservations.reservation', verbose_name='réservation'),
        ),
    ]
