# Generated by Django 6.0.6 on 2026-06-22 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_document'),
        ('organizations', '0001_initial'),
        ('reservations', '0002_reservation_return_time_reservation_trip_type'),
        ('trips', '0002_trip_leg_alter_trip_reservation'),
        ('vehicles', '0005_vehicle_fuel_specs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('reservation', 'leg'), name='uniq_trip_reservation_leg'),
        ),
    ]
