# Generated by Django 6.0.6 on 2026-07-29 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_trip_uniq_trip_reservation_leg'),
        ('vehicles', '0005_vehicle_fuel_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='planned_arrival_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='arrivée prévue'),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_departure_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='départ prévu'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Planifiée'), ('departed', 'Départ effectué'), ('in_progress', 'En cours'), ('returned', 'Retour effectué'), ('closed', 'Clôturée'), ('cancelled', 'Annulée')], db_index=True, default='scheduled', max_length=16, verbose_name='statut'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='vehicles.vehicle', verbose_name='véhicule'),
        ),
    ]
