# Generated by Django 6.0.6 on 2026-07-29 23:13

import apps.core.db
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_document'),
        ('organizations', '0001_initial'),
        ('reservations', '0002_reservation_return_time_reservation_trip_type'),
        ('trips', '0005_dispatch_p0_no_double_booking'),
        ('vehicles', '0005_vehicle_fuel_specs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='trip',
            name='excl_trip_vehicle_overlap',
        ),
        migrations.RemoveConstraint(
            model_name='trip',
            name='excl_trip_driver_overlap',
        ),
        migrations.AddField(
            model_name='trip',
            name='dispatch_group',
            field=models.UUIDField(blank=True, db_index=True, null=True, verbose_name='groupe de dispatching'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('planned_arrival_at__isnull', False), ('planned_departure_at__isnull', False), ('status__in', ['scheduled', 'departed', 'in_progress', 'returned']), ('vehicle__isnull', False)), expressions=[('vehicle', '='), (apps.core.db.TsTzRange('planned_departure_at', 'planned_arrival_at', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), (django.db.models.functions.comparison.Coalesce('dispatch_group', 'id'), '<>')], name='excl_trip_vehicle_overlap', violation_error_message='Conflit horaire : ce véhicule est déjà engagé sur ce créneau.'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('driver__isnull', False), ('planned_arrival_at__isnull', False), ('planned_departure_at__isnull', False), ('status__in', ['scheduled', 'departed', 'in_progress', 'returned'])), expressions=[('driver', '='), (apps.core.db.TsTzRange('planned_departure_at', 'planned_arrival_at', django.contrib.postgres.fields.ranges.RangeBoundary()), '&&'), (django.db.models.functions.comparison.Coalesce('dispatch_group', 'id'), '<>')], name='excl_trip_driver_overlap', violation_error_message='Conflit horaire : ce chauffeur est déjà engagé sur ce créneau.'),
        ),
    ]
