# Generated by Django 6.0.6 on 2026-07-30 00:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_document'),
        ('organizations', '0001_initial'),
        ('reservations', '0002_reservation_return_time_reservation_trip_type'),
        ('trips', '0006_p5_dispatch_group'),
        ('vehicles', '0005_vehicle_fuel_specs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('planned_departure_at__isnull', True), ('planned_arrival_at__isnull', True), ('planned_departure_at__lte', models.F('planned_arrival_at')), _connector='OR'), name='ck_trip_planned_window_ordered'),
        ),
    ]
