# Generated by Django 6.0.6 on 2026-06-08 16:56

import apps.accounts.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='adresse email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('role', models.CharField(choices=[('super_admin', 'Super administrateur'), ('company_admin', 'Administrateur entreprise'), ('subsidiary_admin', 'Administrateur filiale'), ('fleet_manager', 'Gestionnaire de flotte'), ('department_manager', 'Responsable de service'), ('requester', 'Employé demandeur'), ('driver', 'Chauffeur'), ('finance', 'Comptabilité / Finance'), ('auditor', 'Auditeur')], default='requester', max_length=32, verbose_name='rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès admin')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name="date d'inscription")),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['email'],
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
    ]
