# Generated by Django 6.0.6 on 2026-06-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keycloak_sub',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=255, null=True, unique=True, verbose_name='identifiant Keycloak'),
        ),
    ]
