# Generated by Django 6.0.6 on 2026-06-14 16:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_keycloak_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keycloak_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='ID Keycloak'),
        ),
        migrations.AddField(
            model_name='user',
            name='keycloak_sync_error',
            field=models.TextField(blank=True, default='', verbose_name='erreur de synchro Keycloak'),
        ),
        migrations.AddField(
            model_name='user',
            name='keycloak_sync_status',
            field=models.CharField(choices=[('pending', 'À synchroniser'), ('synced', 'Synchronisé'), ('error', 'Erreur'), ('disabled', 'Synchro désactivée')], default='pending', max_length=16, verbose_name='statut synchro Keycloak'),
        ),
        migrations.AddField(
            model_name='user',
            name='keycloak_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dernière synchro Keycloak'),
        ),
        migrations.AddField(
            model_name='user',
            name='keycloak_username',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='username Keycloak'),
        ),
        migrations.CreateModel(
            name='KeycloakSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=32, verbose_name='action')),
                ('status', models.CharField(max_length=16, verbose_name='statut')),
                ('detail', models.TextField(blank=True, default='', verbose_name='détail')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keycloak_sync_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'journal de synchro Keycloak',
                'verbose_name_plural': 'journaux de synchro Keycloak',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_ke_user_id_c04113_idx')],
            },
        ),
    ]
