# Generated by Django 6.0.6 on 2026-10-02 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_revoke_default_password'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='invité le'),
        ),
        migrations.AddField(
            model_name='user',
            name='sessions_revoked_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='sessions révoquées le'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subsidiary',
            field=models.ForeignKey(blank=True, help_text='Vide pour les rôles à périmètre entreprise (super admin, admin entreprise).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organizations.subsidiary', verbose_name='filiale'),
        ),
    ]
