# Generated by Django 6.0.6 on 2026-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_p0_sessions_and_subsidiary_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_admin_set_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='mot de passe fixé par un administrateur le'),
        ),
    ]
