# Generated by Django 6.0.6 on 2026-10-02 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_activated_at(apps, schema_editor):
    """Comptes déjà ouverts avant cette migration : une connexion SSO a eu lieu (`keycloak_sub`
    renseigné) ou un mot de passe local a été choisi. Ils sont marqués activés (date
    d'inscription à défaut de mieux) : une demande d'activation à leur adresse reçoit l'avis
    « compte déjà actif », jamais un code qui réinitialiserait leur mot de passe Keycloak."""
    from django.contrib.auth.hashers import is_password_usable
    from django.db.models import Q

    User = apps.get_model("accounts", "User")
    User.objects.filter(activated_at__isnull=True).exclude(Q(keycloak_sub__isnull=True) | Q(keycloak_sub="")) \
        .update(activated_at=models.F("date_joined"))
    for pk, password, joined in User.objects.filter(activated_at__isnull=True).values_list("pk", "password",
                                                                                          "date_joined"):
        if is_password_usable(password):
            User.objects.filter(pk=pk).update(activated_at=joined)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_p0_password_admin_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='activé le'),
        ),
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('activation', 'Activation du compte'), ('login', 'Connexion (appareil inconnu ou MFA)'), ('device', "Vérification de l'appareil (SSO)")], max_length=16, verbose_name='objet')),
                ('shield_employee_id', models.CharField(blank=True, default='', max_length=64, verbose_name='employé Shield')),
                ('email_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name="empreinte de l'email")),
                ('challenge_hash', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='empreinte du défi')),
                ('code_hash', models.CharField(max_length=64, verbose_name='empreinte du code')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='contexte')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('expires_at', models.DateTimeField(verbose_name='expire le')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentatives')),
                ('max_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='tentatives maximales')),
                ('consumed_at', models.DateTimeField(blank=True, null=True, verbose_name='utilisé / invalidé le')),
                ('sent_count', models.PositiveSmallIntegerField(default=0, verbose_name='envois')),
                ('last_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='dernier envoi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'code de vérification (email)',
                'verbose_name_plural': 'codes de vérification (email)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivationTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret_hash', models.CharField(max_length=64, verbose_name='empreinte du secret')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('shield_employee_id', models.CharField(max_length=64, verbose_name='employé Shield')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('expires_at', models.DateTimeField(verbose_name='expire le')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='utilisé le')),
                ('otp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.emailotp')),
            ],
            options={
                'verbose_name': "ticket d'activation",
                'verbose_name_plural': "tickets d'activation",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='empreinte du cookie')),
                ('label', models.CharField(blank=True, default='', max_length=120, verbose_name='appareil')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='user-agent')),
                ('ip_first', models.GenericIPAddressField(blank=True, null=True, verbose_name='première adresse IP')),
                ('trusted', models.BooleanField(default=False, verbose_name='appareil de confiance')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='vérifié par code le')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ajouté le')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='dernière utilisation')),
                ('expires_at', models.DateTimeField(verbose_name='expire le')),
                ('sessions_revoked_at', models.DateTimeField(blank=True, null=True, verbose_name="sessions de l'appareil fermées le")),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='révoqué le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'appareil reconnu',
                'verbose_name_plural': 'appareils reconnus',
                'ordering': ['-last_used_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['purpose', 'email_hash', '-created_at'], name='accounts_em_purpose_830ded_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['purpose', 'user', '-created_at'], name='accounts_em_purpose_ecf3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='trusteddevice',
            index=models.Index(fields=['user', 'revoked_at'], name='accounts_tr_user_id_081ab0_idx'),
        ),
        migrations.RunPython(backfill_activated_at, migrations.RunPython.noop),
    ]
