# Generated by Django 6.0.6 on 2026-10-03 13:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auth_otp_devices'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(max_length=64, unique=True, verbose_name='empreinte du code')),
                ('client_id', models.CharField(max_length=255, verbose_name='client')),
                ('redirect_uri', models.CharField(max_length=1000, verbose_name='URI de retour')),
                ('nonce', models.CharField(blank=True, max_length=255, verbose_name='nonce')),
                ('code_challenge', models.CharField(blank=True, max_length=128, verbose_name='défi PKCE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('expires_at', models.DateTimeField(verbose_name='expire le')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='utilisé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "autorisation d'activation",
                'verbose_name_plural': "autorisations d'activation",
                'ordering': ['-created_at'],
            },
        ),
    ]
