# Generated by Django 6.0.6 on 2026-10-02 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShieldCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shield_id', models.PositiveIntegerField(unique=True, verbose_name='identifiant Shield')),
                ('uuid', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='UUID Shield')),
                ('tenant', models.PositiveIntegerField(blank=True, null=True, verbose_name='tenant Shield')),
                ('code', models.CharField(blank=True, default='', max_length=64, verbose_name='code')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='active dans Shield')),
                ('mapping_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='correspondance confirmée le')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='vue dans Shield le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='correspondance confirmée par')),
                ('subsidiary', models.ForeignKey(blank=True, help_text='Correspondance confirmée par un administrateur (jamais déduite automatiquement).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shield_companies', to='organizations.subsidiary', verbose_name='filiale K-Express')),
            ],
            options={
                'verbose_name': 'filiale Shield',
                'verbose_name_plural': 'filiales Shield',
                'ordering': ['name', 'shield_id'],
            },
        ),
        migrations.CreateModel(
            name='ShieldDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shield_id', models.PositiveIntegerField(unique=True, verbose_name='identifiant Shield')),
                ('code', models.CharField(blank=True, default='', max_length=64, verbose_name='code')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='nom')),
                ('parent_shield_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='département parent (Shield)')),
                ('mapping_confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='correspondance confirmée le')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='vu dans Shield le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='shield.shieldcompany', verbose_name='filiale Shield')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shield_departments', to='organizations.department', verbose_name='service K-Express')),
                ('mapping_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='correspondance confirmée par')),
            ],
            options={
                'verbose_name': 'département Shield',
                'verbose_name_plural': 'départements Shield',
                'ordering': ['name', 'shield_id'],
            },
        ),
        migrations.CreateModel(
            name='ShieldSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('full', 'Complète'), ('incremental', 'Incrémentale'), ('reconcile', 'Réconciliation')], max_length=16, verbose_name='mode')),
                ('status', models.CharField(choices=[('running', 'En cours'), ('succeeded', 'Réussie'), ('failed', 'Échouée'), ('interrupted', 'Interrompue')], db_index=True, default='running', max_length=16, verbose_name='statut')),
                ('cursor', models.JSONField(blank=True, default=dict, verbose_name='curseur')),
                ('counters', models.JSONField(blank=True, default=dict, verbose_name='compteurs')),
                ('watermark_start', models.DateTimeField(blank=True, null=True, verbose_name='borne de départ')),
                ('watermark_end', models.DateTimeField(blank=True, null=True, verbose_name='borne atteinte')),
                ('resumed_count', models.PositiveIntegerField(default=0, verbose_name='reprises')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='début')),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='dernier signe de vie')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('error', models.TextField(blank=True, default='', verbose_name='erreur')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='déclenchée par')),
            ],
            options={
                'verbose_name': 'synchronisation Shield',
                'verbose_name_plural': 'synchronisations Shield',
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ShieldEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shield_id', models.PositiveIntegerField(unique=True, verbose_name='identifiant Shield')),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True, verbose_name='UUID Shield')),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254, verbose_name='email professionnel')),
                ('first_name', models.CharField(blank=True, default='', max_length=150, verbose_name='prénom')),
                ('last_name', models.CharField(blank=True, default='', max_length=150, verbose_name='nom')),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='statut RH')),
                ('job_title', models.CharField(blank=True, default='', max_length=255, verbose_name='fonction')),
                ('matricule', models.CharField(blank=True, default='', max_length=64, verbose_name='matricule')),
                ('manager_shield_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='responsable (Shield)')),
                ('shield_updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='modifié dans Shield le')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='synchronisé le')),
                ('absent_since', models.DateTimeField(blank=True, null=True, verbose_name='absent de Shield depuis')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='lien établi le')),
                ('conflict', models.CharField(blank=True, db_index=True, default='', max_length=32, verbose_name='conflit')),
                ('conflict_note', models.CharField(blank=True, default='', max_length=255, verbose_name='note de résolution')),
                ('user_deactivated_by_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='compte désactivé par la synchro le')),
                ('departure_handled_at', models.DateTimeField(blank=True, null=True, verbose_name='départ traité le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='shield.shieldcompany', verbose_name='filiale Shield')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='shield.shielddepartment', verbose_name='département Shield')),
                ('linked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='lien établi par')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shield_employee', to=settings.AUTH_USER_MODEL, verbose_name='compte K-Express lié')),
                ('last_seen_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='shield.shieldsyncrun', verbose_name="dernière synchro l'ayant vu")),
            ],
            options={
                'verbose_name': 'employé Shield',
                'verbose_name_plural': 'employés Shield',
                'ordering': ['last_name', 'first_name', 'shield_id'],
            },
        ),
        migrations.AddIndex(
            model_name='shieldsyncrun',
            index=models.Index(fields=['mode', 'status', '-started_at'], name='shield_shie_mode_1797db_idx'),
        ),
    ]
