# Generated by Django 6.0.6 on 2026-10-02 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shieldemployee',
            name='link_email_accepted',
            field=models.CharField(blank=True, default='', max_length=254, verbose_name='email Shield accepté au lien'),
        ),
        migrations.AddField(
            model_name='shieldemployee',
            name='transfer_pending_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='mutation en attente de correspondance depuis'),
        ),
    ]
