# Generated by Django 6.0.6 on 2026-09-29 15:48

import apps.finance.models
import django.contrib.postgres.constraints
import django.db.models.deletion
import django.db.models.functions.comparison
import uuid
from django.conf import settings
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('trips', '0007_p5bis_window_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # `=` sur des colonnes scalaires dans la contrainte d'exclusion GIST : idempotent.
        BtreeGistExtension(),
        migrations.CreateModel(
            name='TripPricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('amount_per_km', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant par km')),
                ('currency', models.CharField(default='XOF', max_length=8, verbose_name='devise')),
                ('valid_from', models.DateField(verbose_name='début de validité')),
                ('valid_until', models.DateField(blank=True, help_text="Vide : jusqu'à nouvel ordre.", null=True, verbose_name='fin de validité')),
                ('scope', models.CharField(choices=[('global', 'Global'), ('subsidiary', 'Filiale'), ('vehicle_type', 'Type de véhicule'), ('subsidiary_vehicle_type', 'Filiale + type de véhicule')], default='global', max_length=24, verbose_name='périmètre')),
                ('vehicle_type', models.CharField(blank=True, choices=[('sedan', 'Berline'), ('suv', 'SUV / 4x4'), ('pickup', 'Pick-up'), ('van', 'Utilitaire / Van'), ('bus', 'Bus / Minibus'), ('truck', 'Camion'), ('motorcycle', 'Moto'), ('other', 'Autre')], max_length=20, verbose_name='type de véhicule')),
                ('active', models.BooleanField(default=True, verbose_name='actif')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('reason', models.TextField(verbose_name='motif du changement')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_pricing_rules', to='organizations.subsidiary', verbose_name='filiale')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par')),
            ],
            options={
                'verbose_name': 'barème kilométrique',
                'verbose_name_plural': 'barèmes kilométriques',
                'ordering': ['-valid_from'],
                'permissions': [('view_trip_cost', 'Voir le coût des courses'), ('view_vehicle_cost', 'Voir le coût des véhicules'), ('view_expenses', 'Voir les dépenses'), ('manage_expenses', 'Saisir et corriger les dépenses'), ('manage_trip_pricing', 'Gérer le barème kilométrique'), ('manage_budgets', 'Gérer les budgets'), ('export_financial_reports', 'Exporter les rapports financiers')],
            },
        ),
        migrations.CreateModel(
            name='TripPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_version', models.PositiveIntegerField(blank=True, null=True, verbose_name='version du barème')),
                ('amount_per_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='tarif/km appliqué')),
                ('currency', models.CharField(default='XOF', max_length=8, verbose_name='devise')),
                ('priced_on', models.DateField(blank=True, help_text='Date retenue pour choisir le barème.', null=True, verbose_name='date de tarification')),
                ('estimated_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='distance estimée (km)')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='coût kilométrique estimé')),
                ('estimated_at', models.DateTimeField(blank=True, null=True, verbose_name='estimé le')),
                ('actual_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='distance réelle (km)')),
                ('actual_distance_source', models.CharField(blank=True, max_length=16, verbose_name='source de la distance réelle')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='coût kilométrique réel')),
                ('actual_at', models.DateTimeField(blank=True, null=True, verbose_name='réel calculé le')),
                ('frozen_at', models.DateTimeField(blank=True, null=True, verbose_name='figé le')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='trips.trip', verbose_name='course')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='finance.trippricingrule', verbose_name='barème appliqué')),
            ],
            options={
                'verbose_name': 'coût kilométrique de course',
                'verbose_name_plural': 'coûts kilométriques de course',
            },
        ),
        migrations.AddConstraint(
            model_name='trippricingrule',
            constraint=models.CheckConstraint(condition=models.Q(('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='ck_pricing_period_ordered'),
        ),
        migrations.AddConstraint(
            model_name='trippricingrule',
            constraint=models.CheckConstraint(condition=models.Q(('amount_per_km__gt', 0)), name='ck_pricing_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='trippricingrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('scope', 'global'), ('subsidiary__isnull', True), ('vehicle_type', '')), models.Q(('scope', 'subsidiary'), ('subsidiary__isnull', False), ('vehicle_type', '')), models.Q(('scope', 'vehicle_type'), ('subsidiary__isnull', True), models.Q(('vehicle_type', ''), _negated=True)), models.Q(('scope', 'subsidiary_vehicle_type'), ('subsidiary__isnull', False), models.Q(('vehicle_type', ''), _negated=True)), _connector='OR'), name='ck_pricing_scope_criteria'),
        ),
        migrations.AddConstraint(
            model_name='trippricingrule',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('active', True)), expressions=[(apps.finance.models.DateRange('valid_from', 'valid_until', models.Value('[]')), '&&'), ('scope', '='), (django.db.models.functions.comparison.Coalesce(django.db.models.functions.comparison.Cast('subsidiary_id', models.TextField()), models.Value('')), '='), ('vehicle_type', '=')], name='ex_pricing_no_overlap'),
        ),
    ]
