# Generated by Django 6.0.6 on 2026-09-29 23:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_p7_dispatch_suggestions'),
        ('expenses', '0005_f2_expense_workflow'),
        ('finance', '0002_f1_real_cost'),
        ('organizations', '0001_initial'),
        ('trips', '0007_p5bis_window_constraint'),
        ('vehicles', '0006_protect_vehicle_costs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_required_from', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='justificatif obligatoire à partir de')),
                ('depreciation_method', models.CharField(choices=[('linear', 'Linéaire')], default='linear', max_length=16, verbose_name="méthode d'amortissement")),
                ('currency', models.CharField(default='XOF', max_length=8, verbose_name='devise')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'paramètres Finance',
                'verbose_name_plural': 'paramètres Finance',
            },
        ),
        migrations.CreateModel(
            name='FinancialAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('trip', 'Course'), ('mission', 'Mission'), ('vehicle', 'Véhicule'), ('expense', 'Dépense'), ('fuel_log', 'Plein'), ('electric_charge', 'Recharge'), ('maintenance', 'Maintenance'), ('insurance', 'Assurance'), ('other', 'Autre')], max_length=16, verbose_name='objet')),
                ('source_id', models.UUIDField(blank=True, null=True, verbose_name="identifiant de l'objet")),
                ('category', models.CharField(blank=True, max_length=16, verbose_name='nature')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant')),
                ('currency', models.CharField(default='XOF', max_length=8, verbose_name='devise')),
                ('reason', models.TextField(verbose_name='motif')),
                ('status', models.CharField(choices=[('pending', 'À approuver'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], db_index=True, default='pending', max_length=10, verbose_name='statut')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='décidé le')),
                ('decision_comment', models.TextField(blank=True, verbose_name='commentaire de décision')),
            ],
            options={
                'verbose_name': 'ajustement financier',
                'verbose_name_plural': 'ajustements financiers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invoice', 'Facture'), ('receipt', 'Reçu'), ('fuel_ticket', 'Ticket carburant'), ('toll_ticket', 'Ticket de péage'), ('parking', 'Stationnement'), ('garage_invoice', 'Facture garage'), ('charging', 'Recharge électrique'), ('other', 'Autre')], default='other', max_length=16, verbose_name='type')),
                ('file', models.FileField(upload_to='finance/attachments/%Y/%m/', verbose_name='fichier')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name="nom d'origine")),
                ('content_type', models.CharField(blank=True, max_length=100, verbose_name='type MIME')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='taille (octets)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'justificatif',
                'verbose_name_plural': 'justificatifs',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='trippricingrule',
            options={'ordering': ['-valid_from'], 'permissions': [('view_trip_cost', 'Voir le coût des courses'), ('view_vehicle_cost', 'Voir le coût des véhicules'), ('view_expenses', 'Voir les coûts agrégés (dépenses, énergie, charges)'), ('manage_expenses', 'Saisir pleins, recharges, maintenance et charges véhicule'), ('manage_trip_pricing', 'Gérer le barème kilométrique'), ('manage_budgets', 'Gérer les budgets et centres de coût'), ('export_financial_reports', 'Exporter les rapports financiers'), ('close_financial_period', 'Clôturer un mois comptable'), ('view_expense', 'Consulter les dépenses et leurs justificatifs'), ('create_expense', 'Créer une dépense'), ('submit_expense', 'Soumettre une dépense'), ('validate_expense', 'Valider, rejeter une dépense ; approuver un ajustement'), ('pay_expense', 'Marquer une dépense payée'), ('cancel_expense', 'Annuler une dépense validée'), ('export_expenses', 'Exporter les dépenses'), ('manage_finance_settings', 'Paramétrer la finance (seuil de justificatif…)')], 'verbose_name': 'barème kilométrique', 'verbose_name_plural': 'barèmes kilométriques'},
        ),
        migrations.RemoveConstraint(
            model_name='costallocation',
            name='uniq_cost_allocation',
        ),
        migrations.AddField(
            model_name='costallocation',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='expenses.expense', verbose_name='dépense de mission répartie'),
        ),
        migrations.AddField(
            model_name='vehiclemonthlycost',
            name='adjustments',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='ajustements comptabilisés sur le mois'),
        ),
        migrations.AddField(
            model_name='vehiclemonthlycost',
            name='other_direct_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='dépenses exceptionnelles (maintenance en course, dépenses)'),
        ),
        migrations.AddField(
            model_name='vehiclemonthlycost',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='coût total du mois'),
        ),
        migrations.AlterField(
            model_name='costallocation',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.financialperiod', verbose_name='période'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='modifié par'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='approbateur'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.costcenter', verbose_name='centre de coût'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustment', to='expenses.expense', verbose_name='dépense portée'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='dispatch.transportmission', verbose_name='mission'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='original_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments_from', to='finance.financialperiod', verbose_name="période d'origine"),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='posting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments_posted', to='finance.financialperiod', verbose_name='période de comptabilisation'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='subsidiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.subsidiary', verbose_name='filiale imputée'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='trips.trip', verbose_name='course'),
        ),
        migrations.AddField(
            model_name='financialadjustment',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='vehicles.vehicle', verbose_name='véhicule'),
        ),
        migrations.AddField(
            model_name='costallocation',
            name='adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.financialadjustment', verbose_name='ajustement de mission réparti'),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('period__isnull', False)), fields=('period', 'trip', 'component'), name='uniq_cost_allocation'),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('expense__isnull', False)), fields=('expense', 'trip'), name='uniq_allocation_expense_trip'),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('adjustment__isnull', False)), fields=('adjustment', 'trip'), name='uniq_allocation_adjustment_trip'),
        ),
        migrations.AddConstraint(
            model_name='costallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('adjustment__isnull', True), ('expense__isnull', True), ('period__isnull', False)), models.Q(('adjustment__isnull', True), ('expense__isnull', False), ('period__isnull', True)), models.Q(('adjustment__isnull', False), ('expense__isnull', True), ('period__isnull', True)), _connector='OR'), name='ck_allocation_single_source'),
        ),
        migrations.AddField(
            model_name='financialattachment',
            name='adjustment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='finance.financialadjustment', verbose_name='ajustement'),
        ),
        migrations.AddField(
            model_name='financialattachment',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='expenses.expense', verbose_name='dépense'),
        ),
        migrations.AddField(
            model_name='financialattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='déposé par'),
        ),
        migrations.AddConstraint(
            model_name='financesettings',
            constraint=models.CheckConstraint(condition=models.Q(('receipt_required_from__isnull', True), ('receipt_required_from__gte', 0), _connector='OR'), name='ck_settings_receipt_threshold'),
        ),
        migrations.AddIndex(
            model_name='financialadjustment',
            index=models.Index(fields=['subsidiary', 'status'], name='finance_fin_subsidi_25bd84_idx'),
        ),
        migrations.AddConstraint(
            model_name='financialadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='ck_adjustment_amount_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='financialattachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('adjustment__isnull', True), ('expense__isnull', False)), models.Q(('adjustment__isnull', False), ('expense__isnull', True)), _connector='OR'), name='ck_attachment_single_parent'),
        ),
    ]
