# Generated by Django 6.0.6 on 2026-10-01 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_f2_adjustments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemonthlycost',
            name='cumulative_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='coût cumulé à la clôture'),
        ),
        migrations.AlterField(
            model_name='financialadjustment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auteur'),
        ),
        migrations.AlterField(
            model_name='financialperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='clôturée par'),
        ),
    ]
