# Generated by Django 6.0.6 on 2026-10-02 10:22

import apps.finance.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_f2_review_hardening'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trippricingrule',
            options={'ordering': ['-valid_from'], 'permissions': [('view_trip_cost', 'Voir le coût des courses'), ('view_vehicle_cost', 'Voir le coût des véhicules'), ('view_expenses', 'Voir les coûts agrégés (dépenses, énergie, charges)'), ('manage_expenses', 'Saisir pleins, recharges, maintenance et charges véhicule'), ('manage_trip_pricing', 'Gérer le barème kilométrique'), ('manage_budgets', 'Gérer les budgets et centres de coût'), ('export_financial_reports', 'Exporter les rapports financiers'), ('close_financial_period', 'Clôturer un mois comptable'), ('view_expense', 'Consulter les dépenses et leurs justificatifs'), ('create_expense', 'Créer une dépense'), ('submit_expense', 'Soumettre une dépense'), ('validate_expense', 'Valider, rejeter une dépense ; approuver un ajustement'), ('pay_expense', 'Marquer une dépense payée'), ('cancel_expense', 'Annuler une dépense validée'), ('export_expenses', 'Exporter les dépenses'), ('manage_finance_settings', 'Paramétrer la finance (seuil de justificatif…)'), ('view_budgets', 'Consulter les budgets et leur suivi'), ('approve_budget', 'Approuver un budget')], 'verbose_name': 'barème kilométrique', 'verbose_name_plural': 'barèmes kilométriques'},
        ),
        migrations.AddField(
            model_name='financesettings',
            name='budget_alert_thresholds',
            field=models.JSONField(blank=True, default=apps.finance.models.default_budget_thresholds, verbose_name="seuils d'alerte budgétaire (%)"),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(verbose_name='exercice')),
                ('name', models.CharField(max_length=160, verbose_name='libellé')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('approved', 'Approuvé'), ('archived', 'Archivé')], default='draft', max_length=10, verbose_name='statut')),
                ('currency', models.CharField(default='XOF', max_length=8, verbose_name='devise')),
                ('alert_thresholds', models.JSONField(blank=True, null=True, verbose_name="seuils d'alerte (%)")),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approuvé le')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='approuvé par')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('subsidiary', models.ForeignKey(blank=True, help_text='Vide : budget du groupe.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='organizations.subsidiary', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'budget',
                'verbose_name_plural': 'budgets',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(blank=True, help_text="Vide : toute l'année.", null=True, verbose_name='mois')),
                ('category', models.CharField(blank=True, choices=[('energy', 'Énergie'), ('maintenance', 'Maintenance'), ('insurance', 'Assurance'), ('fixed_charges', 'Charges fixes'), ('toll', 'Péage'), ('parking', 'Stationnement'), ('washing', 'Lavage'), ('road_fees', 'Frais de route'), ('allowance', 'Indemnités'), ('lodging', 'Hébergement'), ('repair', 'Réparation en mission'), ('fine', 'Amende'), ('unexpected', 'Imprévu'), ('other', 'Autre')], max_length=16, verbose_name='catégorie')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant prévu')),
                ('alert_thresholds', models.JSONField(blank=True, null=True, verbose_name="seuils d'alerte (%)")),
                ('label', models.CharField(blank=True, max_length=160, verbose_name='libellé')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='finance.budget', verbose_name='budget')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='finance.costcenter', verbose_name='centre de coût')),
                ('subsidiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.subsidiary', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'ligne budgétaire',
                'verbose_name_plural': 'lignes budgétaires',
                'ordering': ['budget', 'month', 'category'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.PositiveSmallIntegerField(verbose_name='seuil (%)')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='consommation au déclenchement (%)')),
                ('consumed', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='engagé + réalisé')),
                ('planned', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='prévu')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='déclenchée le')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', to='finance.budgetline', verbose_name='ligne')),
            ],
            options={
                'verbose_name': 'alerte budgétaire',
                'verbose_name_plural': 'alertes budgétaires',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='montant précédent')),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='nouveau montant')),
                ('reason', models.TextField(blank=True, verbose_name='motif')),
                ('kind', models.CharField(choices=[('initial', 'Création'), ('draft', 'Brouillon'), ('revision', 'Révision')], max_length=12, verbose_name='nature')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='finance.budgetline', verbose_name='ligne')),
            ],
            options={
                'verbose_name': 'révision budgétaire',
                'verbose_name_plural': 'révisions budgétaires',
                'ordering': ['at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BudgetActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('energy', 'Énergie'), ('maintenance', 'Maintenance'), ('insurance', 'Assurance'), ('fixed_charges', 'Charges fixes'), ('toll', 'Péage'), ('parking', 'Stationnement'), ('washing', 'Lavage'), ('road_fees', 'Frais de route'), ('allowance', 'Indemnités'), ('lodging', 'Hébergement'), ('repair', 'Réparation en mission'), ('fine', 'Amende'), ('unexpected', 'Imprévu'), ('other', 'Autre')], max_length=16, verbose_name='catégorie')),
                ('engaged', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='engagé')),
                ('realised', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='réalisé')),
                ('disbursed', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='décaissé')),
                ('frozen_at', models.DateTimeField(auto_now_add=True, verbose_name='figé le')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.costcenter', verbose_name='centre de coût')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_actuals', to='finance.financialperiod', verbose_name='période')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.subsidiary', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'réalisé budgétaire figé',
                'verbose_name_plural': 'réalisés budgétaires figés',
                'constraints': [models.UniqueConstraint(fields=('period', 'subsidiary', 'cost_center', 'category'), name='uniq_budget_actual_cell', nulls_distinct=False)],
            },
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_budget_line_amount'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.CheckConstraint(condition=models.Q(('month__isnull', True), models.Q(('month__gte', 1), ('month__lte', 12)), _connector='OR'), name='ck_budget_line_month'),
        ),
        migrations.AddConstraint(
            model_name='budgetline',
            constraint=models.UniqueConstraint(fields=('budget', 'month', 'subsidiary', 'cost_center', 'category'), name='uniq_budget_line_axes', nulls_distinct=False),
        ),
        migrations.AddConstraint(
            model_name='budgetalert',
            constraint=models.UniqueConstraint(fields=('line', 'threshold'), name='uniq_budget_alert'),
        ),
    ]
