# Generated by Django 6.0.6 on 2026-10-02 13:36

from django.db import migrations, models


def mark_frozen_periods(apps, schema_editor):
    """Un mois clos dont le réalisé budgétaire a déjà été figé (lignes `BudgetActual`) est
    marqué comme tel ; les mois clos avant F3 restent sans marque (lus sur leurs pièces)."""
    period = apps.get_model("finance", "FinancialPeriod")
    actual = apps.get_model("finance", "BudgetActual")
    frozen = actual.objects.values_list("period_id", flat=True).distinct()
    for p in period.objects.filter(pk__in=frozen, status="closed", budget_frozen_at__isnull=True):
        period.objects.filter(pk=p.pk).update(budget_frozen_at=p.closed_at)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_f3_budgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialperiod',
            name='budget_frozen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='réalisé budgétaire figé le'),
        ),
        migrations.AlterField(
            model_name='budgetalert',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='consommation au déclenchement (%)'),
        ),
        migrations.RunPython(mark_frozen_periods, migrations.RunPython.noop),
    ]
