# Generated by Django 6.0.6 on 2026-07-29 23:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0004_driver_document'),
        ('organizations', '0001_initial'),
        ('trips', '0005_dispatch_p0_no_double_booking'),
        ('vehicles', '0005_vehicle_fuel_specs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code')),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('dispatched', 'Affectée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='planned', max_length=12, verbose_name='statut')),
                ('planned_departure_at', models.DateTimeField(blank=True, null=True, verbose_name='départ prévu')),
                ('planned_arrival_at', models.DateTimeField(blank=True, null=True, verbose_name='arrivée prévue')),
                ('planned_distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='distance consolidée (km)')),
                ('planned_duration_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée consolidée (min)')),
                ('consolidated_geometry', models.JSONField(blank=True, default=list, verbose_name='tracé consolidé')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_missions', to=settings.AUTH_USER_MODEL, verbose_name='créée par')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='drivers.driver', verbose_name='chauffeur')),
                ('subsidiary', models.ForeignKey(blank=True, help_text='Filiale qui fournit le véhicule. NE définit pas la visibilité.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operated_missions', to='organizations.subsidiary', verbose_name='filiale opératrice')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'mission de transport',
                'verbose_name_plural': 'missions de transport',
                'ordering': ['-planned_departure_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveSmallIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='liaison active')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_additions', to=settings.AUTH_USER_MODEL, verbose_name='ajoutée par')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_links', to='trips.trip', verbose_name='course')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='dispatch.transportmission', verbose_name='mission')),
            ],
            options={
                'verbose_name': 'course de mission',
                'verbose_name_plural': 'courses de mission',
                'ordering': ['sequence', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordre')),
                ('kind', models.CharField(choices=[('pickup', 'Prise en charge'), ('dropoff', 'Dépose')], max_length=8, verbose_name='nature')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='lieu')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('contact', models.CharField(blank=True, max_length=255, verbose_name='contact')),
                ('passenger_count', models.PositiveSmallIntegerField(default=0, verbose_name='passagers')),
                ('planned_time', models.DateTimeField(blank=True, null=True, verbose_name='horaire prévu')),
                ('actual_time', models.DateTimeField(blank=True, null=True, verbose_name='horaire réel')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_stops', to='trips.trip', verbose_name='course')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='dispatch.transportmission', verbose_name='mission')),
            ],
            options={
                'verbose_name': 'arrêt de mission',
                'verbose_name_plural': 'arrêts de mission',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='transportmission',
            index=models.Index(fields=['status', 'planned_departure_at'], name='dispatch_tr_status_2c1315_idx'),
        ),
        migrations.AddConstraint(
            model_name='missiontrip',
            constraint=models.UniqueConstraint(fields=('mission', 'trip'), name='uniq_mission_trip'),
        ),
        migrations.AddConstraint(
            model_name='missiontrip',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('trip',), name='uniq_trip_in_active_mission'),
        ),
        migrations.AddConstraint(
            model_name='missionstop',
            constraint=models.UniqueConstraint(fields=('mission', 'order'), name='uniq_mission_stop_order'),
        ),
    ]
