# Generated by Django 6.0.6 on 2026-07-30 01:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_p5_transport_mission'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('group', 'Regrouper des courses'), ('vehicle', 'Affecter un véhicule'), ('driver', 'Affecter un chauffeur')], max_length=10, verbose_name='nature')),
                ('payload', models.JSONField(default=dict, verbose_name='proposition')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='données utilisées')),
                ('rationale', models.TextField(blank=True, verbose_name='explication')),
                ('score', models.FloatField(default=0.0, verbose_name='pertinence')),
                ('rank', models.PositiveSmallIntegerField(default=0, verbose_name='rang')),
                ('status', models.CharField(choices=[('proposed', 'Proposée'), ('accepted', 'Acceptée'), ('modified', 'Acceptée avec modification'), ('rejected', 'Rejetée'), ('stale', 'Périmée')], default='proposed', max_length=10, verbose_name='statut')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('generated_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_suggestions', to='organizations.subsidiary', verbose_name='filiale concernée')),
            ],
            options={
                'verbose_name': 'suggestion de dispatching',
                'verbose_name_plural': 'suggestions de dispatching',
                'ordering': ['rank', '-score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('accept', 'Acceptée telle quelle'), ('modify', 'Acceptée avec modification'), ('reject', 'Rejetée')], max_length=10, verbose_name='décision')),
                ('applied_changes', models.JSONField(blank=True, default=dict, verbose_name='modifications appliquées')),
                ('before', models.JSONField(blank=True, default=dict, verbose_name='état avant')),
                ('after', models.JSONField(blank=True, default=dict, verbose_name='état après')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_decisions', to=settings.AUTH_USER_MODEL, verbose_name='décidée par')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='dispatch.dispatchsuggestion', verbose_name='suggestion')),
            ],
            options={
                'verbose_name': 'décision de dispatching',
                'verbose_name_plural': 'décisions de dispatching',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispatchsuggestion',
            index=models.Index(fields=['status', 'kind'], name='dispatch_di_status_090d26_idx'),
        ),
    ]
