# Generated by Django 6.0.6 on 2026-10-02 16:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carplan', '0001_c1_initial'),
        ('vehicles', '0006_protect_vehicle_costs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carplanpolicy',
            options={'ordering': ['name'], 'permissions': [('view_carplan', 'Consulter les attributions Car Plan de son périmètre'), ('manage_carplan_assignments', 'Gérer les attributions Car Plan (demande, attribution, remise, restitution)'), ('approve_carplan_assignments', 'Valider, refuser, suspendre, prolonger une attribution Car Plan'), ('manage_carplan_policies', 'Gérer les politiques Car Plan'), ('manage_carplan_vehicle_modes', "Changer le mode d'exploitation d'un véhicule (flotte, fonction, service)"), ('view_carplan_costs', 'Consulter les coûts Car Plan'), ('manage_carplan_contributions', 'Enregistrer les participations financières des bénéficiaires'), ('export_carplan', 'Exporter les données Car Plan'), ('view_carplan_gps', "Demander ou accorder un accès exceptionnel à la position d'un véhicule attribué")], 'verbose_name': 'politique Car Plan', 'verbose_name_plural': 'politiques Car Plan'},
        ),
        migrations.CreateModel(
            name='GpsAccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motive', models.CharField(choices=[('theft', 'Vol ou disparition du véhicule'), ('accident', 'Accident, panne, assistance'), ('security', 'Sécurité du bénéficiaire'), ('legal', "Réquisition d'une autorité"), ('other', 'Autre motif documenté')], max_length=10, verbose_name='motif')),
                ('reason', models.TextField(verbose_name='justification')),
                ('starts_at', models.DateTimeField(verbose_name='du')),
                ('ends_at', models.DateTimeField(verbose_name='au')),
                ('status', models.CharField(choices=[('requested', 'Demandée'), ('approved', 'Accordée'), ('rejected', 'Refusée'), ('revoked', 'Révoquée')], db_index=True, default='requested', max_length=10, verbose_name='statut')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='décidée le')),
                ('decision_note', models.TextField(blank=True, verbose_name='observation')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='révoquée le')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='dernier accès')),
                ('use_count', models.PositiveIntegerField(default=0, verbose_name='accès tracés')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gps_grants', to='carplan.carplanassignment', verbose_name='attribution')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='décidée par')),
                ('grantee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name="bénéficiaire de l'exception")),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='révoquée par')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carplan_gps_grants', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'accès exceptionnel à la position',
                'verbose_name_plural': 'accès exceptionnels à la position',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_carplan_gps_grant_window')],
            },
        ),
    ]
