# Generated by Django 6.0.6 on 2026-06-08 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration', models.CharField(max_length=32, unique=True, verbose_name='immatriculation')),
                ('brand', models.CharField(max_length=80, verbose_name='marque')),
                ('model', models.CharField(max_length=80, verbose_name='modèle')),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Berline'), ('suv', 'SUV / 4x4'), ('pickup', 'Pick-up'), ('van', 'Utilitaire / Van'), ('bus', 'Bus / Minibus'), ('truck', 'Camion'), ('motorcycle', 'Moto'), ('other', 'Autre')], default='sedan', max_length=20, verbose_name='type')),
                ('capacity', models.PositiveSmallIntegerField(default=5, verbose_name='capacité (places)')),
                ('mileage', models.PositiveIntegerField(default=0, verbose_name='kilométrage')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Diesel'), ('hybrid', 'Hybride'), ('electric', 'Électrique'), ('lpg', 'GPL'), ('other', 'Autre')], default='diesel', max_length=20, verbose_name='carburant')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('on_trip', 'En course'), ('maintenance', 'En maintenance'), ('out_of_service', 'Hors service'), ('unavailable', 'Indisponible')], db_index=True, default='available', max_length=20, verbose_name='état')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name="date d'achat")),
                ('purchase_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="valeur d'achat")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/photos/', verbose_name='photo')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.subsidiary', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'véhicule',
                'verbose_name_plural': 'véhicules',
                'ordering': ['registration'],
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('insurance', 'Assurance'), ('technical_inspection', 'Visite technique'), ('registration', 'Carte grise'), ('other', 'Autre')], max_length=24, verbose_name='type de document')),
                ('number', models.CharField(blank=True, max_length=120, verbose_name='numéro')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name="date d'émission")),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True, verbose_name="date d'expiration")),
                ('file', models.FileField(blank=True, null=True, upload_to='vehicles/documents/', verbose_name='fichier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'document véhicule',
                'verbose_name_plural': 'documents véhicule',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('previous_status', models.CharField(blank=True, choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('on_trip', 'En course'), ('maintenance', 'En maintenance'), ('out_of_service', 'Hors service'), ('unavailable', 'Indisponible')], max_length=20, verbose_name='ancien état')),
                ('new_status', models.CharField(choices=[('available', 'Disponible'), ('reserved', 'Réservé'), ('on_trip', 'En course'), ('maintenance', 'En maintenance'), ('out_of_service', 'Hors service'), ('unavailable', 'Indisponible')], max_length=20, verbose_name='nouvel état')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='motif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'historique de statut',
                'verbose_name_plural': 'historiques de statut',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['subsidiary', 'status'], name='vehicles_ve_subsidi_b65ecd_idx'),
        ),
    ]
