# Generated by Django 6.0.6 on 2026-06-12 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='revision_alert_bucket',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=160, verbose_name="compagnie d'assurance")),
                ('policy_number', models.CharField(blank=True, max_length=120, verbose_name='numéro de police')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('expiry_date', models.DateField(db_index=True, verbose_name="date d'expiration")),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='coût')),
                ('document', models.FileField(blank=True, null=True, upload_to='vehicles/insurance/', verbose_name='justificatif')),
                ('last_alert_bucket', models.SmallIntegerField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'assurance véhicule',
                'verbose_name_plural': 'assurances véhicule',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalInspection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_date', models.DateField(blank=True, null=True, verbose_name='dernière visite')),
                ('next_date', models.DateField(db_index=True, verbose_name='prochaine visite')),
                ('center', models.CharField(blank=True, max_length=160, verbose_name='centre de visite')),
                ('result', models.CharField(blank=True, choices=[('passed', 'Favorable'), ('failed', 'Défavorable'), ('', '—')], default='', max_length=12, verbose_name='résultat')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='coût')),
                ('observations', models.TextField(blank=True, verbose_name='observations')),
                ('document', models.FileField(blank=True, null=True, upload_to='vehicles/inspections/', verbose_name='justificatif')),
                ('last_alert_bucket', models.SmallIntegerField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'visite technique',
                'verbose_name_plural': 'visites techniques',
                'ordering': ['-next_date'],
            },
        ),
        migrations.CreateModel(
            name='VehicleRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(verbose_name='date de révision')),
                ('mileage_at_revision', models.PositiveIntegerField(verbose_name='kilométrage à la révision')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='coût')),
                ('provider', models.CharField(blank=True, max_length=160, verbose_name='garage / prestataire')),
                ('document', models.FileField(blank=True, null=True, upload_to='vehicles/revisions/', verbose_name='justificatif')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'révision véhicule',
                'verbose_name_plural': 'révisions véhicule',
                'ordering': ['-mileage_at_revision'],
            },
        ),
    ]
