# Generated by Django 6.0.6 on 2026-06-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_revision_alert_bucket_insurancepolicy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='revision_interval_km',
            field=models.PositiveIntegerField(default=10000, help_text='Ex. Hilux 10 000 km, Duster 5 000 km, camion 15 000 km.', verbose_name='intervalle de révision (km)'),
        ),
    ]
