# Generated by Django 6.0.6 on 2026-06-14 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


# Référentiels préchargés (marché ivoirien). Idempotent via get_or_create.
BRANDS = {
    "Toyota": ["Hilux", "Land Cruiser", "Land Cruiser Prado", "Corolla", "Yaris",
               "Fortuner", "RAV4", "Hiace", "Coaster", "Camry", "Avensis"],
    "Renault": ["Duster", "Kwid", "Logan", "Sandero", "Oroch", "Master", "Trafic",
                "Clio", "Kangoo"],
    "Peugeot": ["208", "308", "3008", "508", "Partner", "Boxer", "Expert", "Landtrek"],
    "Hyundai": ["Tucson", "Santa Fe", "Accent", "Elantra", "Creta", "H-1", "Starex", "i10"],
    "Kia": ["Sportage", "Sorento", "Rio", "Picanto", "Cerato", "K2700"],
    "Nissan": ["Patrol", "X-Trail", "Navara", "Qashqai", "Almera", "Urvan"],
    "Mitsubishi": ["Pajero", "L200", "Outlander", "ASX", "Canter"],
    "Isuzu": ["D-Max", "MU-X", "NPR", "NQR"],
    "Ford": ["Ranger", "Everest", "Transit", "Focus", "F-150"],
    "Volkswagen": ["Amarok", "Tiguan", "Passat", "Golf", "Caddy", "Crafter"],
    "Mercedes-Benz": ["Sprinter", "Vito", "Classe C", "Classe E", "Actros"],
    "BMW": ["Série 3", "Série 5", "X3", "X5"],
    "Land Rover": ["Defender", "Discovery", "Range Rover"],
    "Suzuki": ["Jimny", "Vitara", "Swift", "APV"],
    "Mahindra": ["Scorpio", "Bolero", "XUV500", "Pik Up"],
}

INSURERS = [
    "NSIA Assurances", "SUNU Assurances", "Allianz Côte d'Ivoire", "Saham Assurance",
    "Atlantique Assurances", "Sanlam Assurances", "SIDAM", "Loyale Assurances",
    "GPA Assurances", "SONAM Assurances", "AXA Côte d'Ivoire",
]

INSPECTION_CENTERS = [
    ("SICTA", "Abidjan"),
    ("Quipux Afrique", "Abidjan"),
]


def seed_reference(apps, schema_editor):
    VehicleBrand = apps.get_model("vehicles", "VehicleBrand")
    VehicleModel = apps.get_model("vehicles", "VehicleModel")
    InsuranceCompany = apps.get_model("vehicles", "InsuranceCompany")
    InspectionCenter = apps.get_model("vehicles", "InspectionCenter")

    for brand_name, models_list in BRANDS.items():
        brand, _ = VehicleBrand.objects.get_or_create(name=brand_name)
        for model_name in models_list:
            VehicleModel.objects.get_or_create(brand=brand, name=model_name)
    for name in INSURERS:
        InsuranceCompany.objects.get_or_create(name=name)
    for name, city in INSPECTION_CENTERS:
        InspectionCenter.objects.get_or_create(name=name, defaults={"city": city})


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_revision_interval_km'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionCenter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='centre de visite technique')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='ville')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'centre de visite technique',
                'verbose_name_plural': 'centres de visite technique',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceCompany',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, unique=True, verbose_name="compagnie d'assurance")),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': "compagnie d'assurance",
                'verbose_name_plural': "compagnies d'assurance",
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='marque')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'marque de véhicule',
                'verbose_name_plural': 'marques de véhicule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, verbose_name='modèle')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='vehicles.vehiclebrand', verbose_name='marque')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'modèle de véhicule',
                'verbose_name_plural': 'modèles de véhicule',
                'ordering': ['name'],
                'unique_together': {('brand', 'name')},
            },
        ),
        migrations.RunPython(seed_reference, migrations.RunPython.noop),
    ]
