# Generated by Django 6.0.6 on 2026-06-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_reference_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='battery_capacity_kwh',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='capacité batterie (kWh)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='electric_range_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='autonomie électrique (km)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumption_l100km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='consommation (L/100 km)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tank_capacity_liters',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='capacité réservoir (L)'),
        ),
    ]
