# Generated by Django 6.0.6 on 2026-09-29 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_fuel_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurances', to='vehicles.vehicle', verbose_name='véhicule'),
        ),
        migrations.AlterField(
            model_name='technicalinspection',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='vehicles.vehicle', verbose_name='véhicule'),
        ),
        migrations.AlterField(
            model_name='vehiclerevision',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='vehicles.vehicle', verbose_name='véhicule'),
        ),
    ]
