# Generated by Django 6.0.6 on 2026-10-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_protect_vehicle_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='doc_type',
            field=models.CharField(choices=[('registration', 'Carte grise'), ('insurance', 'Assurance'), ('technical_inspection', 'Visite technique'), ('vignette', 'Vignette'), ('transport_authorization', 'Autorisation de transport'), ('lease_contract', 'Contrat de location / leasing'), ('acquisition_invoice', "Facture d'acquisition"), ('other', 'Autre')], max_length=24, verbose_name='type de document'),
        ),
    ]
