# Generated by Django 6.0.6 on 2026-06-08 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='libellé')),
                ('interval_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='périodicité (km)')),
                ('interval_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='périodicité (jours)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'type de maintenance',
                'verbose_name_plural': 'types de maintenance',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='échéance (date)')),
                ('due_mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='échéance (km)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='vehicles.vehicle', verbose_name='véhicule')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='maintenance.maintenancetype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'échéance de maintenance',
                'verbose_name_plural': 'échéances de maintenance',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], db_index=True, default='planned', max_length=16, verbose_name='statut')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='date prévue')),
                ('performed_date', models.DateField(blank=True, null=True, verbose_name='date réalisée')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name="km à l'intervention")),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='coût')),
                ('provider', models.CharField(blank=True, max_length=255, verbose_name='prestataire')),
                ('downtime_start', models.DateTimeField(blank=True, null=True, verbose_name='immobilisation début')),
                ('downtime_end', models.DateTimeField(blank=True, null=True, verbose_name='immobilisation fin')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.subsidiary', verbose_name='filiale')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='vehicles.vehicle', verbose_name='véhicule')),
                ('maintenance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='maintenance.maintenancetype', verbose_name='type')),
            ],
            options={
                'verbose_name': 'intervention de maintenance',
                'verbose_name_plural': 'interventions de maintenance',
                'ordering': ['-scheduled_date', '-created_at'],
                'indexes': [models.Index(fields=['subsidiary', 'status'], name='maintenance_subsidi_e6bb95_idx')],
            },
        ),
    ]
