# Generated by Django 6.0.6 on 2026-06-12 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        ('trips', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='declared_date',
            field=models.DateField(blank=True, null=True, verbose_name='date de déclaration'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='maintenance/docs/', verbose_name='justificatif'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="coût main-d'œuvre"),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='nature',
            field=models.CharField(choices=[('preventive', 'Maintenance préventive'), ('corrective', 'Maintenance corrective'), ('urgent', 'Réparation urgente'), ('periodic', 'Entretien périodique'), ('other', 'Autre')], db_index=True, default='corrective', max_length=12, verbose_name='nature'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='parts_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='coût pièces'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='maintenance/photos/', verbose_name='photo'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_records', to='trips.trip', verbose_name='course liée'),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='responsable de validation'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='coût total'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='provider',
            field=models.CharField(blank=True, max_length=255, verbose_name='prestataire / garage'),
        ),
        migrations.CreateModel(
            name='BreakdownType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='libellé')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'type de panne',
                'verbose_name_plural': 'types de panne',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='breakdown_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='maintenance.breakdowntype', verbose_name='type de panne'),
        ),
    ]
