# Generated by Django 6.0.6 on 2026-09-29 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenancerecord_declared_date_and_more'),
        ('vehicles', '0006_protect_vehicle_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_records', to='vehicles.vehicle', verbose_name='véhicule'),
        ),
    ]
