# Generated by Django 6.0.6 on 2026-10-02 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_protect_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePlanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('alert', 'Alerte'), ('relaunch', 'Relance'), ('pace', 'Rythme kilométrique en hausse'), ('cleared', 'Alerte levée'), ('done', 'Entretien réalisé'), ('meter', 'Remplacement de compteur'), ('config', 'Paramètres modifiés')], max_length=10, verbose_name='événement')),
                ('level', models.CharField(blank=True, max_length=10, verbose_name='niveau')),
                ('message', models.CharField(blank=True, max_length=500, verbose_name='message')),
                ('recipients', models.PositiveSmallIntegerField(default=0, verbose_name='destinataires')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='détails')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='le')),
            ],
            options={
                'verbose_name': "événement de plan d'entretien",
                'verbose_name_plural': "événements de plan d'entretien",
                'ordering': ['-at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='maintenanceschedule',
            options={'ordering': ['due_date'], 'verbose_name': "plan d'entretien", 'verbose_name_plural': "plans d'entretien"},
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='alert_key',
            field=models.CharField(blank=True, max_length=80, verbose_name='échéance alertée'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='alert_level',
            field=models.CharField(blank=True, max_length=10, verbose_name="niveau d'alerte notifié"),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='alert_notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dernière notification'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='forecast_date',
            field=models.DateField(blank=True, null=True, verbose_name='date prévisionnelle'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='forecast_km_per_day',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='km / jour retenus'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='forecast_method',
            field=models.CharField(blank=True, max_length=20, verbose_name='méthode'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='forecast_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='prévision du'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='interval_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='périodicité (jours) — dérogation'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='interval_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='périodicité (km) — dérogation'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='last_done_date',
            field=models.DateField(blank=True, null=True, verbose_name='dernier entretien (date)'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='last_done_mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='dernier entretien (km)'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='last_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='maintenance.maintenancerecord', verbose_name='dernière intervention'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='next_date',
            field=models.DateField(blank=True, null=True, verbose_name='prochaine échéance calendaire'),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='pace_alert_key',
            field=models.CharField(blank=True, max_length=80, verbose_name='alerte de rythme émise pour'),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='alert_days',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='alerte (jours)'),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='combustion_only',
            field=models.BooleanField(default=False, verbose_name='opération thermique (sans objet sur un véhicule électrique)'),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='kind',
            field=models.CharField(blank=True, choices=[('oil_change', 'Vidange moteur'), ('filters', 'Filtres'), ('tyres', 'Pneumatiques'), ('brakes', 'Freinage'), ('general_service', 'Révision générale'), ('other', 'Autre opération')], default='', max_length=20, verbose_name="nature d'opération"),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='notice_days',
            field=models.PositiveSmallIntegerField(default=14, verbose_name='préavis (jours)'),
        ),
        migrations.AddField(
            model_name='maintenancetype',
            name='urgent_days',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='urgence (jours)'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='due_date',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='date limite imposée'),
        ),
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='due_mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='prochain seuil (km)'),
        ),
        migrations.AddConstraint(
            model_name='maintenancetype',
            constraint=models.UniqueConstraint(condition=models.Q(('kind__in', ['', 'other']), _negated=True), fields=('kind',), name='uniq_maintenance_type_kind'),
        ),
        migrations.AddConstraint(
            model_name='maintenancetype',
            constraint=models.CheckConstraint(condition=models.Q(('alert_days__gte', models.F('urgent_days')), ('notice_days__gte', models.F('alert_days'))), name='ck_maintenance_type_thresholds'),
        ),
        migrations.AddField(
            model_name='maintenanceplanevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='auteur'),
        ),
        migrations.AddField(
            model_name='maintenanceplanevent',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='maintenance.maintenancerecord', verbose_name='intervention'),
        ),
        migrations.AddField(
            model_name='maintenanceplanevent',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='maintenance.maintenanceschedule', verbose_name='plan'),
        ),
    ]
