# Generated by Django 6.0.6 on 2026-06-11 20:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_code', models.CharField(choices=[('super', 'Super sans plomb'), ('gasoil', 'Gasoil')], max_length=10, verbose_name='carburant')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='prix / litre')),
                ('currency', models.CharField(default='XOF', max_length=8, verbose_name='devise')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='source')),
                ('effective_date', models.DateField(verbose_name="date d'effet")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'prix carburant',
                'verbose_name_plural': 'prix carburant',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelConsumptionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('vehicle', 'Véhicule'), ('driver', 'Chauffeur'), ('vehicle_type', 'Type de véhicule'), ('subsidiary', 'Filiale'), ('fleet', 'Flotte')], max_length=16, verbose_name='niveau')),
                ('ref', models.CharField(blank=True, default='', help_text="ID/code de l'objet visé ('' pour la flotte).", max_length=64, verbose_name='référence')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='libellé')),
                ('rate_l_per_100km', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='taux (L/100 km)')),
                ('samples', models.PositiveIntegerField(default=0, verbose_name='courses observées')),
                ('total_km', models.DecimalField(decimal_places=1, default=0, max_digits=12, verbose_name='km cumulés')),
                ('total_liters', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='litres cumulés')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'profil de consommation',
                'verbose_name_plural': 'profils de consommation',
                'ordering': ['scope', 'ref'],
                'unique_together': {('scope', 'ref')},
            },
        ),
    ]
