# Generated by Django 6.0.6 on 2026-07-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelintel', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fuelconsumptionprofile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fuelconsumptionprofile',
            name='unit',
            field=models.CharField(choices=[('L', 'litres'), ('kWh', 'kWh')], default='L', max_length=8, verbose_name='unité'),
        ),
        migrations.AlterField(
            model_name='fuelconsumptionprofile',
            name='rate_l_per_100km',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='taux (par 100 km)'),
        ),
        migrations.AlterField(
            model_name='fuelconsumptionprofile',
            name='total_liters',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='énergie cumulée'),
        ),
        migrations.AlterUniqueTogether(
            name='fuelconsumptionprofile',
            unique_together={('scope', 'ref', 'unit')},
        ),
    ]
