# Generated by Django 6.0.6 on 2026-07-29 22:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuelintel', '0002_p3_energy_units'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricityPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='prix / kWh')),
                ('currency', models.CharField(default='XOF', max_length=8, verbose_name='devise')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='source')),
                ('effective_date', models.DateField(verbose_name="date d'effet")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(blank=True, help_text="Vide = tarif applicable à toute l'entreprise.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electricity_prices', to='organizations.subsidiary', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'prix électricité',
                'verbose_name_plural': 'prix électricité',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
    ]
