# Generated by Django 6.0.6 on 2026-07-30 00:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_p5_transport_mission'),
        ('fuelintel', '0003_p4_electricity'),
        ('organizations', '0001_initial'),
        ('trips', '0007_p5bis_window_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='énergie imputée')),
                ('unit', models.CharField(choices=[('L', 'litres'), ('kWh', 'kWh')], max_length=8, verbose_name='unité')),
                ('allocated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='coût imputé')),
                ('share_ratio', models.FloatField(verbose_name='part (0-1)')),
                ('allocation_rule', models.CharField(max_length=24, verbose_name="clé d'imputation")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_allocations', to='dispatch.transportmission', verbose_name='mission')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='energy_allocations', to='organizations.subsidiary', verbose_name='filiale imputée')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_allocations', to='trips.trip', verbose_name='course')),
            ],
            options={
                'verbose_name': 'imputation énergétique',
                'verbose_name_plural': 'imputations énergétiques',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subsidiary', 'created_at'], name='fuelintel_e_subsidi_132699_idx')],
                'constraints': [models.UniqueConstraint(fields=('mission', 'trip'), name='uniq_allocation_mission_trip')],
            },
        ),
    ]
