# Generated by Django 6.0.6 on 2026-06-08 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField(verbose_name="date de l'incident")),
                ('severity', models.CharField(choices=[('minor', 'Mineur'), ('moderate', 'Modéré'), ('major', 'Majeur'), ('critical', 'Critique')], default='minor', max_length=12, verbose_name='gravité')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'incident chauffeur',
                'verbose_name_plural': 'incidents chauffeur',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120, verbose_name='prénom')),
                ('last_name', models.CharField(max_length=120, verbose_name='nom')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('license_number', models.CharField(blank=True, max_length=64, verbose_name='numéro de permis')),
                ('license_category', models.CharField(blank=True, max_length=32, verbose_name='catégorie de permis')),
                ('license_expiry', models.DateField(blank=True, db_index=True, null=True, verbose_name='expiration du permis')),
                ('is_available', models.BooleanField(db_index=True, default=True, verbose_name='disponible')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='note moyenne')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.subsidiary', verbose_name='filiale')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='compte utilisateur')),
            ],
            options={
                'verbose_name': 'chauffeur',
                'verbose_name_plural': 'chauffeurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='DriverAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField(verbose_name='début')),
                ('end', models.DateTimeField(verbose_name='fin')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='note')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='drivers.driver', verbose_name='chauffeur')),
            ],
            options={
                'verbose_name': 'disponibilité chauffeur',
                'verbose_name_plural': 'disponibilités chauffeur',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='DriverEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.PositiveSmallIntegerField(verbose_name='note (1-5)')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='drivers.driver', verbose_name='chauffeur')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='évaluateur')),
            ],
            options={
                'verbose_name': 'évaluation chauffeur',
                'verbose_name_plural': 'évaluations chauffeur',
                'ordering': ['-created_at'],
            },
        ),
    ]
