# Generated by Django 6.0.6 on 2026-06-14 08:36

from django.db import migrations, models


def backfill_matricules(apps, schema_editor):
    """Attribue un matricule CHF-#### aux chauffeurs existants qui n'en ont pas."""
    Driver = apps.get_model("drivers", "Driver")
    n = 1
    for driver in Driver.objects.filter(matricule__isnull=True).order_by("created_at"):
        while Driver.objects.filter(matricule=f"CHF-{n:04d}").exists():
            n += 1
        driver.matricule = f"CHF-{n:04d}"
        driver.save(update_fields=["matricule"])
        n += 1


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='matricule',
            field=models.CharField(blank=True, help_text='Identifiant interne du chauffeur (généré automatiquement).', max_length=20, null=True, unique=True, verbose_name='matricule'),
        ),
        migrations.RunPython(backfill_matricules, migrations.RunPython.noop),
    ]
