# Generated by Django 6.0.6 on 2026-06-14 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_matricule_autoprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_type', models.CharField(choices=[('license', 'Permis de conduire'), ('id_card', "Pièce d'identité"), ('contract', 'Contrat'), ('medical', 'Certificat médical'), ('other', 'Autre')], default='other', max_length=24, verbose_name='type de document')),
                ('number', models.CharField(blank=True, max_length=120, verbose_name='numéro')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name="date d'émission")),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True, verbose_name="date d'expiration")),
                ('file', models.FileField(blank=True, null=True, upload_to='drivers/documents/', verbose_name='fichier')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='drivers.driver', verbose_name='chauffeur')),
            ],
            options={
                'verbose_name': 'document chauffeur',
                'verbose_name_plural': 'documents chauffeur',
                'ordering': ['expiry_date'],
            },
        ),
    ]
