# Generated by Django 6.0.6 on 2026-10-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0004_driver_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='doc_type',
            field=models.CharField(choices=[('license', 'Permis de conduire'), ('id_card', "Carte nationale d'identité (CNI)"), ('training', 'Attestation de formation'), ('medical', 'Certificat médical'), ('habilitation', 'Habilitation professionnelle'), ('contract', 'Contrat'), ('other', 'Autre')], default='other', max_length=24, verbose_name='type de document'),
        ),
    ]
