# Generated by Django 6.0.6 on 2026-06-08 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('export', 'Export'), ('access', 'Accès')], db_index=True, max_length=12, verbose_name='action')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='identifiant cible')),
                ('target_repr', models.CharField(blank=True, max_length=255, verbose_name='représentation cible')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='modifications')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='adresse IP')),
                ('user_agent', models.CharField(blank=True, max_length=512, verbose_name='user agent')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='type cible')),
            ],
            options={
                'verbose_name': "entrée d'audit",
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'action'], name='audit_audit_actor_i_aad064_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__b61fb0_idx')],
            },
        ),
    ]
