# Generated by Django 6.0.6 on 2026-07-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression'), ('login', 'Connexion'), ('logout', 'Déconnexion'), ('export', 'Export'), ('access', 'Accès'), ('dispatch_decision', 'Décision de dispatching')], db_index=True, max_length=32, verbose_name='action'),
        ),
    ]
