# Generated by Django 6.0.6 on 2026-06-08 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0002_initial'),
        ('organizations', '0001_initial'),
        ('trips', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='web', max_length=10, verbose_name='plateforme')),
                ('push_token', models.CharField(blank=True, max_length=512, verbose_name='jeton push')),
                ('device_id', models.CharField(blank=True, max_length=255, verbose_name='identifiant appareil')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='dernier vu')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='drivers.driver', verbose_name='chauffeur')),
            ],
            options={
                'verbose_name': 'appareil chauffeur',
                'verbose_name_plural': 'appareils chauffeur',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='GeofenceZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('zone_type', models.CharField(choices=[('company', 'Zone entreprise'), ('subsidiary', 'Zone filiale'), ('mission', 'Zone mission'), ('forbidden', 'Zone interdite'), ('parking', 'Zone de stationnement')], default='mission', max_length=12, verbose_name='type de zone')),
                ('polygon', models.JSONField(default=list, verbose_name='polygone (GeoJSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.subsidiary', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'zone géographique',
                'verbose_name_plural': 'zones géographiques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeofenceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('enter', 'Entrée'), ('exit', 'Sortie')], max_length=8, verbose_name='événement')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='warning', max_length=10, verbose_name='gravité')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='horodatage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geofence_alerts', to='trips.trip', verbose_name='course')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_alerts', to='vehicles.vehicle', verbose_name='véhicule')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracking.geofencezone', verbose_name='zone')),
            ],
            options={
                'verbose_name': 'alerte de zone',
                'verbose_name_plural': 'alertes de zone',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='OfflineSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(default=dict, verbose_name='charge utile')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('synced', 'Synchronisé'), ('conflict', 'Conflit'), ('failed', 'Échec')], default='pending', max_length=10, verbose_name='statut')),
                ('points_count', models.PositiveIntegerField(default=0, verbose_name='nombre de points')),
                ('conflict_detail', models.TextField(blank=True, verbose_name='détail conflit')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='synchronisé le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='tracking.driverdevice', verbose_name='appareil')),
            ],
            options={
                'verbose_name': 'journal de synchronisation',
                'verbose_name_plural': 'journaux de synchronisation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteDeviationAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='warning', max_length=10, verbose_name='gravité')),
                ('deviation_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='écart (m)')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('occurred_at', models.DateTimeField(db_index=True, verbose_name='horodatage')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deviation_alerts', to='trips.trip', verbose_name='course')),
            ],
            options={
                'verbose_name': "alerte d'écart d'itinéraire",
                'verbose_name_plural': "alertes d'écart d'itinéraire",
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consented', models.BooleanField(default=False, verbose_name='consentement')),
                ('consented_at', models.DateTimeField(blank=True, null=True, verbose_name='consenti le')),
                ('work_start', models.TimeField(blank=True, null=True, verbose_name='début horaire de travail')),
                ('work_end', models.TimeField(blank=True, null=True, verbose_name='fin horaire de travail')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_consent', to='drivers.driver', verbose_name='chauffeur')),
            ],
            options={
                'verbose_name': 'consentement de tracking',
                'verbose_name_plural': 'consentements de tracking',
            },
        ),
        migrations.CreateModel(
            name='TripRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('origin_label', models.CharField(blank=True, max_length=255, verbose_name='départ')),
                ('origin_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude départ')),
                ('origin_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude départ')),
                ('destination_label', models.CharField(blank=True, max_length=255, verbose_name='destination')),
                ('destination_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude destination')),
                ('destination_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude destination')),
                ('planned_distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='distance estimée (km)')),
                ('planned_duration_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée estimée (min)')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='coût estimé')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='trips.trip', verbose_name='course')),
            ],
            options={
                'verbose_name': 'itinéraire de course',
                'verbose_name_plural': 'itinéraires de course',
            },
        ),
        migrations.CreateModel(
            name='TripTrackingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'En pause'), ('ended', 'Terminée')], db_index=True, default='active', max_length=10, verbose_name='statut')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='début')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='distance totale (km)')),
                ('average_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='vitesse moyenne (km/h)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.subsidiary', verbose_name='filiale')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_sessions', to='trips.trip', verbose_name='course')),
            ],
            options={
                'verbose_name': 'session de tracking',
                'verbose_name_plural': 'sessions de tracking',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TripWaypoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ordre')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='libellé')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='tracking.triproute', verbose_name='itinéraire')),
            ],
            options={
                'verbose_name': "étape d'itinéraire",
                'verbose_name_plural': "étapes d'itinéraire",
                'ordering': ['route', 'order'],
            },
        ),
        migrations.CreateModel(
            name='VehicleLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='vitesse (km/h)')),
                ('heading', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='cap (°)')),
                ('recorded_at', models.DateTimeField(db_index=True, verbose_name='horodatage GPS')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='last_location', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'position véhicule',
                'verbose_name_plural': 'positions véhicule',
            },
        ),
        migrations.CreateModel(
            name='TripLocationPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='longitude')),
                ('speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='vitesse (km/h)')),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='précision (m)')),
                ('recorded_at', models.DateTimeField(db_index=True, verbose_name='horodatage GPS')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='tracking.triptrackingsession', verbose_name='session')),
            ],
            options={
                'verbose_name': 'point GPS',
                'verbose_name_plural': 'points GPS',
                'ordering': ['session', 'recorded_at'],
                'indexes': [models.Index(fields=['session', 'recorded_at'], name='tracking_tr_session_6b9508_idx')],
            },
        ),
    ]
