# Generated by Django 6.0.6 on 2026-06-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triproute',
            name='geometry',
            field=models.JSONField(blank=True, default=list, verbose_name='tracé routier'),
        ),
    ]
