# Generated by Django 6.0.6 on 2026-06-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_triproute_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='triproute',
            name='estimated_fuel_l',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='carburant estimé (L)'),
        ),
    ]
