# Generated by Django 6.0.6 on 2026-06-13 14:51

import django.contrib.gis.db.models.fields
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_triproute_estimated_fuel_l'),
    ]

    operations = [
        # PostGIS doit exister avant toute colonne géométrique (idempotent).
        CreateExtension('postgis'),
        migrations.AddField(
            model_name='geofencezone',
            name='area',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326, verbose_name='zone'),
        ),
        migrations.AddField(
            model_name='triplocationpoint',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='vehiclelocation',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='geofencezone',
            name='polygon',
            field=models.JSONField(default=list, verbose_name='polygone'),
        ),
    ]
