# Generated by Django 6.0.6 on 2026-06-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_backfill_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='triproute',
            name='active_distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='distance recalculée (km)'),
        ),
        migrations.AddField(
            model_name='triproute',
            name='active_duration_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='durée recalculée (min)'),
        ),
        migrations.AddField(
            model_name='triproute',
            name='active_geometry',
            field=models.JSONField(blank=True, default=list, verbose_name='tracé recalculé'),
        ),
        migrations.AddField(
            model_name='triproute',
            name='last_rerouted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dernier recalcul'),
        ),
        migrations.AddField(
            model_name='triproute',
            name='reroute_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='nombre de recalculs'),
        ),
    ]
