# Generated by Django 6.0.6 on 2026-07-29 18:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tracking', '0006_triproute_active_distance_km_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='geofencezone',
            name='category',
            field=models.CharField(blank=True, choices=[('administrative', 'Zone administrative'), ('business', 'Zone métier')], default='', max_length=16, verbose_name='catégorie'),
        ),
        migrations.AddField(
            model_name='geofencezone',
            name='center',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='centre'),
        ),
        migrations.AddField(
            model_name='geofencezone',
            name='center_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude centre'),
        ),
        migrations.AddField(
            model_name='geofencezone',
            name='center_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude centre'),
        ),
        migrations.AddField(
            model_name='geofencezone',
            name='code',
            field=models.SlugField(blank=True, default='', max_length=64, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='geofencezone',
            name='radius_m',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='rayon (m)'),
        ),
        migrations.AddField(
            model_name='triproute',
            name='destination_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_to', to='tracking.geofencezone', verbose_name='zone de destination'),
        ),
        migrations.AddField(
            model_name='triproute',
            name='origin_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes_from', to='tracking.geofencezone', verbose_name='zone de départ'),
        ),
        migrations.AlterField(
            model_name='geofencezone',
            name='zone_type',
            field=models.CharField(choices=[('company', 'Zone entreprise'), ('subsidiary', 'Zone filiale'), ('mission', 'Zone mission'), ('forbidden', 'Zone interdite'), ('parking', 'Zone de stationnement'), ('operational', 'Zone opérationnelle')], default='mission', max_length=12, verbose_name='type de zone'),
        ),
        migrations.AddConstraint(
            model_name='geofencezone',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('subsidiary', 'code'), name='uniq_zone_subsidiary_code'),
        ),
    ]
