# Generated by Django 6.0.6 on 2026-07-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_p1_operational_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='triproute',
            name='estimated_energy_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='énergie estimée (kWh)'),
        ),
    ]
