# Generated by Django 6.0.6 on 2026-07-29 20:05

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('vehicles', '0005_vehicle_fuel_specs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmptyMileageMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField(verbose_name='début de période')),
                ('period_end', models.DateField(verbose_name='fin de période')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='calculé le')),
                ('km_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='km totaux')),
                ('km_loaded', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='km en charge')),
                ('km_empty', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='km à vide')),
                ('loaded_rate', models.FloatField(blank=True, null=True, verbose_name='taux en charge')),
                ('empty_rate', models.FloatField(blank=True, null=True, verbose_name='taux à vide')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.subsidiary', verbose_name='filiale')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'métrique de kilométrage à vide',
                'verbose_name_plural': 'métriques de kilométrage à vide',
                'ordering': ['-period_start', 'vehicle_id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'period_start', 'period_end'), name='uniq_empty_mileage_vehicle_period'), models.CheckConstraint(condition=models.Q(('km_empty', django.db.models.expressions.CombinedExpression(models.F('km_total'), '-', models.F('km_loaded')))), name='ck_empty_equals_total_minus_loaded')],
            },
        ),
        migrations.CreateModel(
            name='OccupancyMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField(verbose_name='début de période')),
                ('period_end', models.DateField(verbose_name='fin de période')),
                ('computed_at', models.DateTimeField(auto_now=True, verbose_name='calculé le')),
                ('trips', models.PositiveIntegerField(default=0, verbose_name='courses')),
                ('hours_in_mission', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='heures en mission')),
                ('hours_available', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='heures disponibles')),
                ('temporal_rate', models.FloatField(blank=True, null=True, verbose_name="taux d'occupation temporelle")),
                ('passengers_carried', models.PositiveIntegerField(default=0, verbose_name='passagers transportés')),
                ('seats_offered', models.PositiveIntegerField(default=0, verbose_name='places offertes')),
                ('fill_rate', models.FloatField(blank=True, null=True, verbose_name='taux de remplissage')),
                ('mutualisation_rate', models.FloatField(blank=True, null=True, verbose_name='taux de mutualisation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.subsidiary', verbose_name='filiale')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': "métrique d'occupation",
                'verbose_name_plural': "métriques d'occupation",
                'ordering': ['-period_start', 'vehicle_id'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'period_start', 'period_end'), name='uniq_occupancy_vehicle_period')],
            },
        ),
    ]
