# Generated by Django 6.0.6 on 2026-06-14 13:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KBotInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, max_length=32, verbose_name='rôle')),
                ('question', models.TextField(verbose_name='question')),
                ('intent', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='intention détectée')),
                ('data_source', models.CharField(default='internal_services', max_length=32, verbose_name='source des données')),
                ('confidence', models.FloatField(default=0.0, verbose_name='score de confiance')),
                ('response_ms', models.PositiveIntegerField(default=0, verbose_name='temps de réponse (ms)')),
                ('injection_flagged', models.BooleanField(db_index=True, default=False, verbose_name='injection détectée')),
                ('refused', models.BooleanField(default=False, verbose_name='refusée')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kbot_interactions', to='organizations.subsidiary', verbose_name='filiale')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kbot_interactions', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'interaction K-BOT',
                'verbose_name_plural': 'interactions K-BOT',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='kbot_kbotin_user_id_fd9786_idx'), models.Index(fields=['injection_flagged'], name='kbot_kbotin_injecti_3a7665_idx')],
            },
        ),
    ]
