# Generated by Django 6.0.6 on 2026-06-08 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('trips', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetBudget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120, verbose_name='libellé')),
                ('period_start', models.DateField(verbose_name='début de période')),
                ('period_end', models.DateField(verbose_name='fin de période')),
                ('allocated', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='montant alloué')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.subsidiary', verbose_name='filiale')),
            ],
            options={
                'verbose_name': 'budget flotte',
                'verbose_name_plural': 'budgets flotte',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('fuel', 'Carburant'), ('maintenance', 'Maintenance'), ('insurance', 'Assurance'), ('toll', 'Péage'), ('fine', 'Amende'), ('unexpected', 'Imprévu'), ('other', 'Autre')], default='other', max_length=16, verbose_name='catégorie')),
                ('label', models.CharField(max_length=255, verbose_name='libellé')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant')),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/misc/', verbose_name='justificatif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.subsidiary', verbose_name='filiale')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'dépense',
                'verbose_name_plural': 'dépenses',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['subsidiary', 'category'], name='expenses_ex_subsidi_6b51b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('liters', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='litres')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='montant')),
                ('price_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='prix au litre')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='km au plein')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/fuel/', verbose_name='ticket')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.subsidiary', verbose_name='filiale')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fuel_logs', to='trips.trip', verbose_name='course')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'plein de carburant',
                'verbose_name_plural': 'pleins de carburant',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['subsidiary', 'date'], name='expenses_fu_subsidi_8ff37c_idx')],
            },
        ),
    ]
