# Generated by Django 6.0.6 on 2026-07-29 22:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_trip'),
        ('organizations', '0001_initial'),
        ('trips', '0005_dispatch_p0_no_double_booking'),
        ('vehicles', '0005_vehicle_fuel_specs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fuellog',
            name='estimated_liters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='litres estimés'),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='fuel_code',
            field=models.CharField(blank=True, choices=[('super', 'Super sans plomb'), ('gasoil', 'Gasoil')], default='', max_length=10, verbose_name='carburant'),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='station',
            field=models.CharField(blank=True, max_length=255, verbose_name='station'),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_fuel_logs', to=settings.AUTH_USER_MODEL, verbose_name='validé par'),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='variance_pct',
            field=models.FloatField(blank=True, null=True, verbose_name='écart estimation / réel (%)'),
        ),
        migrations.CreateModel(
            name='ElectricCharge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True, verbose_name='date')),
                ('battery_capacity_kwh', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='capacité batterie (kWh)')),
                ('soc_start_pct', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='charge initiale (%)')),
                ('soc_end_pct', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='charge finale (%)')),
                ('kwh_recharged', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='énergie rechargée (kWh)')),
                ('kwh_consumed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='énergie consommée depuis la dernière recharge (kWh)')),
                ('range_estimate_km', models.PositiveIntegerField(blank=True, null=True, verbose_name='autonomie estimée (km)')),
                ('charger', models.CharField(blank=True, max_length=255, verbose_name='borne de recharge')),
                ('charge_type', models.CharField(choices=[('ac_slow', 'Recharge lente (AC)'), ('ac_fast', 'Recharge accélérée (AC)'), ('dc_rapid', 'Recharge rapide (DC)'), ('other', 'Autre')], default='ac_slow', max_length=10, verbose_name='type de recharge')),
                ('duration_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='durée de recharge (min)')),
                ('kwh_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='prix du kWh')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='coût total')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='km à la recharge')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/charges/', verbose_name='justificatif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('subsidiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.subsidiary', verbose_name='filiale')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electric_charges', to='trips.trip', verbose_name='course')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_charges', to=settings.AUTH_USER_MODEL, verbose_name='validé par')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electric_charges', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'recharge électrique',
                'verbose_name_plural': 'recharges électriques',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['subsidiary', 'date'], name='expenses_el_subsidi_a641d2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('soc_start_pct__isnull', True), ('soc_start_pct__lte', 100), _connector='OR'), name='ck_charge_soc_start_pct'), models.CheckConstraint(condition=models.Q(('soc_end_pct__isnull', True), ('soc_end_pct__lte', 100), _connector='OR'), name='ck_charge_soc_end_pct')],
            },
        ),
    ]
