# Generated by Django 6.0.6 on 2026-09-29 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


OVERLAPPING = ("fuel", "maintenance", "insurance")


def flag_legacy_overlaps(apps, schema_editor):
    """D2 : les dépenses « carburant / maintenance / assurance » antérieures recouvrent les
    tables dédiées. Elles sont marquées « reprise à faire » : exclues des coûts (pour ne pas
    compter deux fois), conservées et listées pour être reprises — jamais supprimées."""
    Expense = apps.get_model("expenses", "Expense")
    Expense.objects.filter(category__in=OVERLAPPING, source_type="").update(source_type="legacy")


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_p7_dispatch_suggestions'),
        ('drivers', '0004_driver_document'),
        ('expenses', '0003_p4_electricity'),
        ('finance', '0002_f1_real_cost'),
        ('organizations', '0001_initial'),
        ('trips', '0007_p5bis_window_constraint'),
        ('vehicles', '0006_protect_vehicle_costs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.costcenter', verbose_name='centre de coût'),
        ),
        migrations.AddField(
            model_name='expense',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='drivers.driver', verbose_name='chauffeur'),
        ),
        migrations.AddField(
            model_name='expense',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='dispatch.transportmission', verbose_name='mission'),
        ),
        migrations.AddField(
            model_name='expense',
            name='source_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='identifiant de la source'),
        ),
        migrations.AddField(
            model_name='expense',
            name='source_reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='référence (facture, bon…)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='source_type',
            field=models.CharField(blank=True, choices=[('', 'Dépense autonome'), ('fuel_log', 'Plein de carburant'), ('electric_charge', 'Recharge électrique'), ('maintenance', 'Maintenance'), ('insurance', 'Assurance'), ('inspection', 'Visite technique'), ('revision', 'Révision'), ('vehicle_charge', 'Charge véhicule'), ('other', 'Autre référence'), ('legacy', 'Reprise à faire')], default='', max_length=16, verbose_name='enregistrement source'),
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.CharField(blank=True, max_length=255, verbose_name='fournisseur'),
        ),
        migrations.AlterField(
            model_name='electriccharge',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='electric_charges', to='vehicles.vehicle', verbose_name='véhicule'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('fuel', 'Carburant'), ('maintenance', 'Maintenance'), ('insurance', 'Assurance'), ('toll', 'Péage'), ('parking', 'Stationnement'), ('washing', 'Lavage'), ('road_fees', 'Frais de route'), ('allowance', 'Indemnités'), ('lodging', 'Hébergement'), ('repair', 'Réparation en mission'), ('fine', 'Amende'), ('unexpected', 'Imprévu'), ('other', 'Autre')], default='other', max_length=16, verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='vehicles.vehicle', verbose_name='véhicule'),
        ),
        migrations.AlterField(
            model_name='fuellog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fuel_logs', to='vehicles.vehicle', verbose_name='véhicule'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['subsidiary', 'date'], name='expenses_ex_subsidi_5537be_idx'),
        ),
        migrations.RunPython(flag_legacy_overlaps, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='ck_expense_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__in', ('fuel', 'maintenance', 'insurance')), _negated=True), ('source_type__in', ('fuel_log', 'electric_charge', 'maintenance', 'insurance', 'inspection', 'revision', 'vehicle_charge', 'legacy')), _connector='OR'), name='ck_expense_overlap_needs_source'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', ('', 'other', 'legacy')), ('source_id__isnull', False), _connector='OR'), name='ck_expense_source_identified'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(condition=models.Q(('source_id__isnull', False)), fields=('source_type', 'source_id'), name='uniq_expense_source'),
        ),
    ]
