# Generated by Django 6.0.6 on 2026-09-29 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def validate_existing(apps, schema_editor):
    """Les dépenses antérieures au circuit F2 étaient déjà comptées : elles deviennent
    « validées » (datées de leur saisie), avec une ligne d'historique qui le dit — sans quoi
    elles disparaîtraient des coûts déjà publiés."""
    Expense = apps.get_model("expenses", "Expense")
    History = apps.get_model("expenses", "ExpenseStatusHistory")
    rows = []
    for expense in Expense.objects.all().only("pk", "amount", "created_at", "cost_center_id"):
        rows.append(History(expense_id=expense.pk, action="migration", from_status="",
                            to_status="validated", amount=expense.amount,
                            cost_center_id=expense.cost_center_id,
                            comment="Reprise F2 : dépense antérieure au circuit, déjà comptée."))
    Expense.objects.all().update(status="validated", validated_at=models.F("created_at"))
    History.objects.bulk_create(rows, batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_f1_expense_imputation'),
        ('finance', '0002_f1_real_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='accounting_exported_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="exportée vers l'ERP le"),
        ),
        migrations.AddField(
            model_name='expense',
            name='accounting_reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='référence comptable (ERP)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='original_category',
            field=models.CharField(blank=True, max_length=16, verbose_name="catégorie d'origine"),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='payée le'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='payée par'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('transfer', 'Virement'), ('check', 'Chèque'), ('cash', 'Espèces'), ('mobile_money', 'Mobile money'), ('card', 'Carte'), ('other', 'Autre')], max_length=16, verbose_name='mode de paiement'),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120, verbose_name='référence de paiement'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt_required',
            field=models.BooleanField(default=False, verbose_name='justificatif exigé'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='réconciliée le'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='réconciliée par'),
        ),
        migrations.AddField(
            model_name='expense',
            name='reconciliation',
            field=models.JSONField(blank=True, default=dict, verbose_name='réconciliation'),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('to_validate', 'À valider'), ('validated', 'Validée'), ('paid', 'Payée'), ('rejected', 'Rejetée'), ('cancelled', 'Annulée')], db_index=True, default='draft', max_length=12, verbose_name='statut'),
        ),
        migrations.AddField(
            model_name='expense',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='soumise le'),
        ),
        migrations.AddField(
            model_name='expense',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='validée le'),
        ),
        migrations.AddField(
            model_name='expense',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='validée par'),
        ),
        migrations.CreateModel(
            name='ExpenseStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=24, verbose_name='action')),
                ('from_status', models.CharField(blank=True, max_length=12, verbose_name='ancien statut')),
                ('to_status', models.CharField(max_length=12, verbose_name='nouveau statut')),
                ('at', models.DateTimeField(auto_now_add=True, verbose_name='date / heure')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('reason', models.TextField(blank=True, verbose_name='motif')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="montant au moment de l'action")),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='détails')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.costcenter', verbose_name='centre de coût')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='expenses.expense', verbose_name='dépense')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'historique de dépense',
                'verbose_name_plural': 'historiques de dépense',
                'ordering': ['at', 'id'],
            },
        ),
        migrations.RunPython(validate_existing, migrations.RunPython.noop),
]
