# Generated by Django 6.0.6 on 2026-10-02 14:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_p7_dispatch_suggestions'),
        ('drivers', '0004_driver_document'),
        ('expenses', '0005_f2_expense_workflow'),
        ('finance', '0006_f3_review_hardening'),
        ('organizations', '0001_initial'),
        ('trips', '0007_p5bis_window_constraint'),
        ('vehicles', '0006_protect_vehicle_costs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expense',
            name='ck_expense_overlap_needs_source',
        ),
        migrations.AlterField(
            model_name='expense',
            name='source_type',
            field=models.CharField(blank=True, choices=[('', 'Dépense autonome'), ('fuel_log', 'Plein de carburant'), ('electric_charge', 'Recharge électrique'), ('maintenance', 'Maintenance'), ('insurance', 'Assurance'), ('inspection', 'Visite technique'), ('revision', 'Révision'), ('vehicle_charge', 'Charge véhicule'), ('lease', 'Loyer de leasing / location'), ('other', 'Autre référence'), ('legacy', 'Reprise à faire')], default='', max_length=16, verbose_name='enregistrement source'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__in', ('fuel', 'maintenance', 'insurance')), _negated=True), ('source_type__in', ('fuel_log', 'electric_charge', 'maintenance', 'insurance', 'inspection', 'revision', 'vehicle_charge', 'lease', 'legacy')), _connector='OR'), name='ck_expense_overlap_needs_source'),
        ),
    ]
