# Generated by Django 6.0.6 on 2026-06-08 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('reservation_submitted', 'Demande soumise'), ('reservation_approved', 'Demande validée'), ('reservation_rejected', 'Demande refusée'), ('vehicle_assigned', 'Véhicule affecté'), ('driver_assigned', 'Chauffeur affecté'), ('departure_reminder', 'Rappel avant départ'), ('return_expected', 'Retour attendu'), ('return_late', 'Retard de retour'), ('insurance_expiring', 'Assurance proche expiration'), ('inspection_expiring', 'Visite technique proche expiration'), ('maintenance_due', 'Maintenance à prévoir'), ('trip_departed', 'Départ de course'), ('trip_arrived', 'Arrivée destination'), ('geofence_exit', 'Sortie de zone'), ('route_deviation', 'Véhicule hors itinéraire'), ('gps_signal_lost', 'Perte de signal GPS'), ('incident_reported', 'Incident déclaré'), ('other', 'Autre')], default='other', max_length=32, verbose_name='type')),
                ('channel', models.CharField(choices=[('in_app', 'Notification interne'), ('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('push', 'Push')], default='in_app', max_length=10, verbose_name='canal')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='info', max_length=10, verbose_name='gravité')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('link', models.CharField(blank=True, max_length=512, verbose_name='lien')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='lu')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lu le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('reservation_submitted', 'Demande soumise'), ('reservation_approved', 'Demande validée'), ('reservation_rejected', 'Demande refusée'), ('vehicle_assigned', 'Véhicule affecté'), ('driver_assigned', 'Chauffeur affecté'), ('departure_reminder', 'Rappel avant départ'), ('return_expected', 'Retour attendu'), ('return_late', 'Retard de retour'), ('insurance_expiring', 'Assurance proche expiration'), ('inspection_expiring', 'Visite technique proche expiration'), ('maintenance_due', 'Maintenance à prévoir'), ('trip_departed', 'Départ de course'), ('trip_arrived', 'Arrivée destination'), ('geofence_exit', 'Sortie de zone'), ('route_deviation', 'Véhicule hors itinéraire'), ('gps_signal_lost', 'Perte de signal GPS'), ('incident_reported', 'Incident déclaré'), ('other', 'Autre')], max_length=32, verbose_name='type')),
                ('in_app', models.BooleanField(default=True, verbose_name='interne')),
                ('email', models.BooleanField(default=True, verbose_name='email')),
                ('sms', models.BooleanField(default=False, verbose_name='SMS')),
                ('whatsapp', models.BooleanField(default=False, verbose_name='WhatsApp')),
                ('push', models.BooleanField(default=True, verbose_name='push')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'préférence de notification',
                'verbose_name_plural': 'préférences de notification',
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
