# Generated by Django 6.0.6 on 2026-06-12 18:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reservation_submitted', 'Demande soumise'), ('reservation_approved', 'Demande validée'), ('reservation_rejected', 'Demande refusée'), ('vehicle_assigned', 'Véhicule affecté'), ('driver_assigned', 'Chauffeur affecté'), ('departure_reminder', 'Rappel avant départ'), ('return_expected', 'Retour attendu'), ('return_late', 'Retard de retour'), ('insurance_expiring', 'Assurance proche expiration'), ('inspection_expiring', 'Visite technique proche expiration'), ('maintenance_due', 'Maintenance à prévoir'), ('trip_departed', 'Départ de course'), ('trip_arrived', 'Arrivée destination'), ('geofence_exit', 'Sortie de zone'), ('route_deviation', 'Véhicule hors itinéraire'), ('gps_signal_lost', 'Perte de signal GPS'), ('incident_reported', 'Incident déclaré'), ('revision_due', 'Révision à prévoir'), ('vehicle_non_compliant', 'Véhicule non conforme'), ('reservation_created', 'Demande créée'), ('reservation_updated', 'Demande modifiée'), ('reservation_cancelled', 'Demande annulée'), ('trip_closed', 'Course clôturée'), ('expense_added', 'Dépense ajoutée'), ('fuel_declared', 'Plein de carburant déclaré'), ('fuel_anomaly', 'Consommation carburant anormale'), ('fuel_price_updated', 'Prix carburant mis à jour'), ('fuel_budget_exceeded', 'Budget carburant dépassé'), ('maintenance_declared', 'Panne / maintenance déclarée'), ('maintenance_done', 'Maintenance terminée'), ('vehicle_immobilized', 'Véhicule immobilisé'), ('vehicle_back', 'Véhicule remis en service'), ('other', 'Autre')], default='other', max_length=32, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('reservation_submitted', 'Demande soumise'), ('reservation_approved', 'Demande validée'), ('reservation_rejected', 'Demande refusée'), ('vehicle_assigned', 'Véhicule affecté'), ('driver_assigned', 'Chauffeur affecté'), ('departure_reminder', 'Rappel avant départ'), ('return_expected', 'Retour attendu'), ('return_late', 'Retard de retour'), ('insurance_expiring', 'Assurance proche expiration'), ('inspection_expiring', 'Visite technique proche expiration'), ('maintenance_due', 'Maintenance à prévoir'), ('trip_departed', 'Départ de course'), ('trip_arrived', 'Arrivée destination'), ('geofence_exit', 'Sortie de zone'), ('route_deviation', 'Véhicule hors itinéraire'), ('gps_signal_lost', 'Perte de signal GPS'), ('incident_reported', 'Incident déclaré'), ('revision_due', 'Révision à prévoir'), ('vehicle_non_compliant', 'Véhicule non conforme'), ('reservation_created', 'Demande créée'), ('reservation_updated', 'Demande modifiée'), ('reservation_cancelled', 'Demande annulée'), ('trip_closed', 'Course clôturée'), ('expense_added', 'Dépense ajoutée'), ('fuel_declared', 'Plein de carburant déclaré'), ('fuel_anomaly', 'Consommation carburant anormale'), ('fuel_price_updated', 'Prix carburant mis à jour'), ('fuel_budget_exceeded', 'Budget carburant dépassé'), ('maintenance_declared', 'Panne / maintenance déclarée'), ('maintenance_done', 'Maintenance terminée'), ('vehicle_immobilized', 'Véhicule immobilisé'), ('vehicle_back', 'Véhicule remis en service'), ('other', 'Autre')], max_length=32, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('to_email', models.EmailField(max_length=254, verbose_name='adresse')),
                ('subject', models.CharField(max_length=255, verbose_name='sujet')),
                ('body', models.TextField(verbose_name='corps')),
                ('status', models.CharField(choices=[('sent', 'Envoyé'), ('failed', 'Échec'), ('disabled', 'Email désactivé'), ('pref_off', 'Désactivé par préférence')], db_index=True, max_length=10, verbose_name='statut')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='erreur')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='notifications.notification', verbose_name='notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'email envoyé',
                'verbose_name_plural': 'emails envoyés',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(choices=[('reservation_submitted', 'Demande soumise'), ('reservation_approved', 'Demande validée'), ('reservation_rejected', 'Demande refusée'), ('vehicle_assigned', 'Véhicule affecté'), ('driver_assigned', 'Chauffeur affecté'), ('departure_reminder', 'Rappel avant départ'), ('return_expected', 'Retour attendu'), ('return_late', 'Retard de retour'), ('insurance_expiring', 'Assurance proche expiration'), ('inspection_expiring', 'Visite technique proche expiration'), ('maintenance_due', 'Maintenance à prévoir'), ('trip_departed', 'Départ de course'), ('trip_arrived', 'Arrivée destination'), ('geofence_exit', 'Sortie de zone'), ('route_deviation', 'Véhicule hors itinéraire'), ('gps_signal_lost', 'Perte de signal GPS'), ('incident_reported', 'Incident déclaré'), ('revision_due', 'Révision à prévoir'), ('vehicle_non_compliant', 'Véhicule non conforme'), ('reservation_created', 'Demande créée'), ('reservation_updated', 'Demande modifiée'), ('reservation_cancelled', 'Demande annulée'), ('trip_closed', 'Course clôturée'), ('expense_added', 'Dépense ajoutée'), ('fuel_declared', 'Plein de carburant déclaré'), ('fuel_anomaly', 'Consommation carburant anormale'), ('fuel_price_updated', 'Prix carburant mis à jour'), ('fuel_budget_exceeded', 'Budget carburant dépassé'), ('maintenance_declared', 'Panne / maintenance déclarée'), ('maintenance_done', 'Maintenance terminée'), ('vehicle_immobilized', 'Véhicule immobilisé'), ('vehicle_back', 'Véhicule remis en service'), ('other', 'Autre')], max_length=32, unique=True, verbose_name='type de notification')),
                ('subject', models.CharField(default='[Kaydan Express] {title}', max_length=255, verbose_name='sujet')),
                ('body', models.TextField(default='{message}\n\nAccéder : {link}', verbose_name='corps')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': "modèle d'email",
                'verbose_name_plural': "modèles d'email",
            },
        ),
    ]
