# Generated by Django 6.0.6 on 2026-06-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='key',
            field=models.CharField(choices=[('reservation_submitted', 'Demande soumise'), ('reservation_approved', 'Demande validée'), ('reservation_rejected', 'Demande refusée'), ('vehicle_assigned', 'Véhicule affecté'), ('driver_assigned', 'Chauffeur affecté'), ('departure_reminder', 'Rappel avant départ'), ('return_expected', 'Retour attendu'), ('return_late', 'Retard de retour'), ('insurance_expiring', 'Assurance proche expiration'), ('inspection_expiring', 'Visite technique proche expiration'), ('maintenance_due', 'Maintenance à prévoir'), ('trip_departed', 'Départ de course'), ('trip_arrived', 'Arrivée destination'), ('geofence_exit', 'Sortie de zone'), ('route_deviation', 'Véhicule hors itinéraire'), ('route_recalculated', 'Itinéraire recalculé'), ('gps_signal_lost', 'Perte de signal GPS'), ('incident_reported', 'Incident déclaré'), ('revision_due', 'Révision à prévoir'), ('vehicle_non_compliant', 'Véhicule non conforme'), ('reservation_created', 'Demande créée'), ('reservation_updated', 'Demande modifiée'), ('reservation_cancelled', 'Demande annulée'), ('trip_closed', 'Course clôturée'), ('expense_added', 'Dépense ajoutée'), ('fuel_declared', 'Plein de carburant déclaré'), ('fuel_anomaly', 'Consommation carburant anormale'), ('fuel_price_updated', 'Prix carburant mis à jour'), ('fuel_budget_exceeded', 'Budget carburant dépassé'), ('maintenance_declared', 'Panne / maintenance déclarée'), ('maintenance_done', 'Maintenance terminée'), ('vehicle_immobilized', 'Véhicule immobilisé'), ('vehicle_back', 'Véhicule remis en service'), ('other', 'Autre')], max_length=32, unique=True, verbose_name='type de notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reservation_submitted', 'Demande soumise'), ('reservation_approved', 'Demande validée'), ('reservation_rejected', 'Demande refusée'), ('vehicle_assigned', 'Véhicule affecté'), ('driver_assigned', 'Chauffeur affecté'), ('departure_reminder', 'Rappel avant départ'), ('return_expected', 'Retour attendu'), ('return_late', 'Retard de retour'), ('insurance_expiring', 'Assurance proche expiration'), ('inspection_expiring', 'Visite technique proche expiration'), ('maintenance_due', 'Maintenance à prévoir'), ('trip_departed', 'Départ de course'), ('trip_arrived', 'Arrivée destination'), ('geofence_exit', 'Sortie de zone'), ('route_deviation', 'Véhicule hors itinéraire'), ('route_recalculated', 'Itinéraire recalculé'), ('gps_signal_lost', 'Perte de signal GPS'), ('incident_reported', 'Incident déclaré'), ('revision_due', 'Révision à prévoir'), ('vehicle_non_compliant', 'Véhicule non conforme'), ('reservation_created', 'Demande créée'), ('reservation_updated', 'Demande modifiée'), ('reservation_cancelled', 'Demande annulée'), ('trip_closed', 'Course clôturée'), ('expense_added', 'Dépense ajoutée'), ('fuel_declared', 'Plein de carburant déclaré'), ('fuel_anomaly', 'Consommation carburant anormale'), ('fuel_price_updated', 'Prix carburant mis à jour'), ('fuel_budget_exceeded', 'Budget carburant dépassé'), ('maintenance_declared', 'Panne / maintenance déclarée'), ('maintenance_done', 'Maintenance terminée'), ('vehicle_immobilized', 'Véhicule immobilisé'), ('vehicle_back', 'Véhicule remis en service'), ('other', 'Autre')], default='other', max_length=32, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(choices=[('reservation_submitted', 'Demande soumise'), ('reservation_approved', 'Demande validée'), ('reservation_rejected', 'Demande refusée'), ('vehicle_assigned', 'Véhicule affecté'), ('driver_assigned', 'Chauffeur affecté'), ('departure_reminder', 'Rappel avant départ'), ('return_expected', 'Retour attendu'), ('return_late', 'Retard de retour'), ('insurance_expiring', 'Assurance proche expiration'), ('inspection_expiring', 'Visite technique proche expiration'), ('maintenance_due', 'Maintenance à prévoir'), ('trip_departed', 'Départ de course'), ('trip_arrived', 'Arrivée destination'), ('geofence_exit', 'Sortie de zone'), ('route_deviation', 'Véhicule hors itinéraire'), ('route_recalculated', 'Itinéraire recalculé'), ('gps_signal_lost', 'Perte de signal GPS'), ('incident_reported', 'Incident déclaré'), ('revision_due', 'Révision à prévoir'), ('vehicle_non_compliant', 'Véhicule non conforme'), ('reservation_created', 'Demande créée'), ('reservation_updated', 'Demande modifiée'), ('reservation_cancelled', 'Demande annulée'), ('trip_closed', 'Course clôturée'), ('expense_added', 'Dépense ajoutée'), ('fuel_declared', 'Plein de carburant déclaré'), ('fuel_anomaly', 'Consommation carburant anormale'), ('fuel_price_updated', 'Prix carburant mis à jour'), ('fuel_budget_exceeded', 'Budget carburant dépassé'), ('maintenance_declared', 'Panne / maintenance déclarée'), ('maintenance_done', 'Maintenance terminée'), ('vehicle_immobilized', 'Véhicule immobilisé'), ('vehicle_back', 'Véhicule remis en service'), ('other', 'Autre')], max_length=32, verbose_name='type'),
        ),
    ]
